//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.08 at 01:14:07 PM CET 
//


package it.csi.gatefire.ca.infocert;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "genderOrPlaceOfBirthOrDateOfBirthOrCountryOfCitizenshipOrCountryOfResidence"
})
@XmlRootElement(name = "directoryAttributes")
public class DirectoryAttributes {

    @XmlElements({
        @XmlElement(name = "gender", required = true, type = Gender.class),
        @XmlElement(name = "placeOfBirth", required = true, type = PlaceOfBirth.class),
        @XmlElement(name = "dateOfBirth", required = true, type = DateOfBirth.class),
        @XmlElement(name = "countryOfCitizenship", required = true, type = CountryOfCitizenship.class),
        @XmlElement(name = "countryOfResidence", required = true, type = CountryOfResidence.class)
    })
    protected List<Object> genderOrPlaceOfBirthOrDateOfBirthOrCountryOfCitizenshipOrCountryOfResidence;

    /**
     * Gets the value of the genderOrPlaceOfBirthOrDateOfBirthOrCountryOfCitizenshipOrCountryOfResidence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the genderOrPlaceOfBirthOrDateOfBirthOrCountryOfCitizenshipOrCountryOfResidence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGenderOrPlaceOfBirthOrDateOfBirthOrCountryOfCitizenshipOrCountryOfResidence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Gender }
     * {@link PlaceOfBirth }
     * {@link DateOfBirth }
     * {@link CountryOfCitizenship }
     * {@link CountryOfResidence }
     * 
     * 
     */
    public List<Object> getGenderOrPlaceOfBirthOrDateOfBirthOrCountryOfCitizenshipOrCountryOfResidence() {
        if (genderOrPlaceOfBirthOrDateOfBirthOrCountryOfCitizenshipOrCountryOfResidence == null) {
            genderOrPlaceOfBirthOrDateOfBirthOrCountryOfCitizenshipOrCountryOfResidence = new ArrayList<Object>();
        }
        return this.genderOrPlaceOfBirthOrDateOfBirthOrCountryOfCitizenshipOrCountryOfResidence;
    }

}
