//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.08 at 01:14:07 PM CET 
//


package it.csi.gatefire.ca.infocert;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "properties"
})
@XmlRootElement(name = "issuer")
public class Issuer {

    @XmlElements({
        @XmlElement(name = "C", required = true, type = C.class),
        @XmlElement(name = "O", required = true, type = O.class),
        @XmlElement(name = "ORGID", required = true, type = ORGID.class),
        @XmlElement(name = "OU", required = true, type = OU.class),
        @XmlElement(name = "L", required = true, type = L.class),
        @XmlElement(name = "SUR", required = true, type = SUR.class),
        @XmlElement(name = "SER", required = true, type = SER.class),
        @XmlElement(name = "GIVEN", required = true, type = GIVEN.class),
        @XmlElement(name = "DNQUALIF", required = true, type = DNQUALIF.class),
        @XmlElement(name = "TITLE", required = true, type = TITLE.class),
        @XmlElement(name = "CN", required = true, type = CN.class),
        @XmlElement(name = "EMAIL", required = true, type = EMAIL.class),
        @XmlElement(name = "DOM", required = true, type = DOM.class),
        @XmlElement(name = "PSEUD", required = true, type = PSEUD.class),
        @XmlElement(name = "DESCR", required = true, type = DESCR.class),
        @XmlElement(name = "PROV", required = true, type = PROV.class),
        @XmlElement(name = "oid", required = true, type = Oid.class)
    })
    protected List<Object> properties;

    /**
     * Gets the value of the cOrOOrOUOrLOrSUROrSEROrGIVENOrDNQUALIFOrTITLEOrCNOrEMAILOrDOMOrPSEUDOrDESCROrPROVOrOid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cOrOOrOUOrLOrSUROrSEROrGIVENOrDNQUALIFOrTITLEOrCNOrEMAILOrDOMOrPSEUDOrDESCROrPROVOrOid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCOrOOrOUOrLOrSUROrSEROrGIVENOrDNQUALIFOrTITLEOrCNOrEMAILOrDOMOrPSEUDOrDESCROrPROVOrOid().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link C }
     * {@link O }
     * {@link OU }
     * {@link L }
     * {@link SUR }
     * {@link SER }
     * {@link GIVEN }
     * {@link DNQUALIF }
     * {@link TITLE }
     * {@link CN }
     * {@link EMAIL }
     * {@link DOM }
     * {@link PSEUD }
     * {@link DESCR }
     * {@link PROV }
     * {@link Oid }
     * 
     * 
     */
    public List<Object> getProperties() {
        if (properties == null) {
        	properties = new ArrayList<Object>();
        }
        return this.properties;
    }

}
