//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.08 at 01:14:07 PM CET 
//


package it.csi.gatefire.ca.infocert;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "policyID",
    "policyQualifierList"
})
@XmlRootElement(name = "policyInformation")
public class PolicyInformation {

    @XmlElement(required = true)
    protected String policyID;
    protected PolicyQualifierList policyQualifierList;

    /**
     * Gets the value of the policyID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyID() {
        return policyID;
    }

    /**
     * Sets the value of the policyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyID(String value) {
        this.policyID = value;
    }

    /**
     * Gets the value of the policyQualifierList property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyQualifierList }
     *     
     */
    public PolicyQualifierList getPolicyQualifierList() {
        return policyQualifierList;
    }

    /**
     * Sets the value of the policyQualifierList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyQualifierList }
     *     
     */
    public void setPolicyQualifierList(PolicyQualifierList value) {
        this.policyQualifierList = value;
    }

}
