//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.08 at 01:14:07 PM CET 
//


package it.csi.gatefire.ca.infocert;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "qcComplianceOrQcLimitValueOrQcRetensionPeriodOrQcSSCD"
})
@XmlRootElement(name = "qcStatements")
public class QcStatements {

    @XmlElements({
        @XmlElement(name = "qcCompliance", required = true, type = QcCompliance.class),
        @XmlElement(name = "qcLimitValue", required = true, type = QcLimitValue.class),
        @XmlElement(name = "qcRetensionPeriod", required = true, type = QcRetensionPeriod.class),
        @XmlElement(name = "qcSSCD", required = true, type = QcSSCD.class)
    })
    protected List<Object> qcComplianceOrQcLimitValueOrQcRetensionPeriodOrQcSSCD;

    /**
     * Gets the value of the qcComplianceOrQcLimitValueOrQcRetensionPeriodOrQcSSCD property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qcComplianceOrQcLimitValueOrQcRetensionPeriodOrQcSSCD property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQcComplianceOrQcLimitValueOrQcRetensionPeriodOrQcSSCD().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QcCompliance }
     * {@link QcLimitValue }
     * {@link QcRetensionPeriod }
     * {@link QcSSCD }
     * 
     * 
     */
    public List<Object> getQcComplianceOrQcLimitValueOrQcRetensionPeriodOrQcSSCD() {
        if (qcComplianceOrQcLimitValueOrQcRetensionPeriodOrQcSSCD == null) {
            qcComplianceOrQcLimitValueOrQcRetensionPeriodOrQcSSCD = new ArrayList<Object>();
        }
        return this.qcComplianceOrQcLimitValueOrQcRetensionPeriodOrQcSSCD;
    }

}
