package it.csi.gatefire.dbhelper.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import it.csi.gatefire.dbhelper.model.GatefireDFunzione;
import it.csi.gatefire.dbhelper.model.GatefireDFunzioneExample;

public interface GatefireDFunzioneMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_funzione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	long countByExample(GatefireDFunzioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_funzione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	int deleteByExample(GatefireDFunzioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_funzione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	int deleteByPrimaryKey(String codice);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_funzione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	int insert(GatefireDFunzione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_funzione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	int insertSelective(GatefireDFunzione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_funzione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	List<GatefireDFunzione> selectByExample(GatefireDFunzioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_funzione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	GatefireDFunzione selectByPrimaryKey(String codice);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_funzione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	int updateByExampleSelective(@Param("record") GatefireDFunzione record,
			@Param("example") GatefireDFunzioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_funzione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	int updateByExample(@Param("record") GatefireDFunzione record, @Param("example") GatefireDFunzioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_funzione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	int updateByPrimaryKeySelective(GatefireDFunzione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_funzione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	int updateByPrimaryKey(GatefireDFunzione record);
}