/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gatefire.dbhelper.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import it.csi.gatefire.dbhelper.model.GatefireDRepository;
import it.csi.gatefire.dbhelper.model.GatefireDRepositoryExample;

public interface GatefireDRepositoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_repository
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	long countByExample(GatefireDRepositoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_repository
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	int deleteByExample(GatefireDRepositoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_repository
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	int deleteByPrimaryKey(String codice);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_repository
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	int insert(GatefireDRepository record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_repository
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	int insertSelective(GatefireDRepository record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_repository
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	List<GatefireDRepository> selectByExample(GatefireDRepositoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_repository
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	GatefireDRepository selectByPrimaryKey(String codice);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_repository
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	int updateByExampleSelective(@Param("record") GatefireDRepository record,
			@Param("example") GatefireDRepositoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_repository
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	int updateByExample(@Param("record") GatefireDRepository record,
			@Param("example") GatefireDRepositoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_repository
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	int updateByPrimaryKeySelective(GatefireDRepository record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_repository
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	int updateByPrimaryKey(GatefireDRepository record);
}