package it.csi.gatefire.dbhelper.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import it.csi.gatefire.dbhelper.model.GatefireRRepositoryFunzione;
import it.csi.gatefire.dbhelper.model.GatefireRRepositoryFunzioneExample;

public interface GatefireRRepositoryFunzioneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_repository_funzione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    long countByExample(GatefireRRepositoryFunzioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_repository_funzione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int deleteByExample(GatefireRRepositoryFunzioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_repository_funzione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_repository_funzione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int insert(GatefireRRepositoryFunzione record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_repository_funzione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int insertSelective(GatefireRRepositoryFunzione record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_repository_funzione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    List<GatefireRRepositoryFunzione> selectByExample(GatefireRRepositoryFunzioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_repository_funzione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    GatefireRRepositoryFunzione selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_repository_funzione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int updateByExampleSelective(@Param("record") GatefireRRepositoryFunzione record, @Param("example") GatefireRRepositoryFunzioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_repository_funzione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int updateByExample(@Param("record") GatefireRRepositoryFunzione record, @Param("example") GatefireRRepositoryFunzioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_repository_funzione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int updateByPrimaryKeySelective(GatefireRRepositoryFunzione record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_repository_funzione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int updateByPrimaryKey(GatefireRRepositoryFunzione record);
}