package it.csi.gatefire.dbhelper.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import it.csi.gatefire.dbhelper.model.GatefireDVersione;
import it.csi.gatefire.dbhelper.model.GatefireDVersioneExample;

public interface GatefireDVersioneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    long countByExample(GatefireDVersioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int deleteByExample(GatefireDVersioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int insert(GatefireDVersione record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int insertSelective(GatefireDVersione record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    List<GatefireDVersione> selectByExample(GatefireDVersioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    GatefireDVersione selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int updateByExampleSelective(@Param("record") GatefireDVersione record, @Param("example") GatefireDVersioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int updateByExample(@Param("record") GatefireDVersione record, @Param("example") GatefireDVersioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int updateByPrimaryKeySelective(GatefireDVersione record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int updateByPrimaryKey(GatefireDVersione record);
}