package it.csi.gatefire.dbhelper.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import it.csi.gatefire.dbhelper.model.GatefireLEvento;
import it.csi.gatefire.dbhelper.model.GatefireLEventoExample;

public interface GatefireLEventoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	long countByExample(GatefireLEventoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	int deleteByExample(GatefireLEventoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	int insert(GatefireLEvento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	int insertSelective(GatefireLEvento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	List<GatefireLEvento> selectByExample(GatefireLEventoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	GatefireLEvento selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	int updateByExampleSelective(@Param("record") GatefireLEvento record,
			@Param("example") GatefireLEventoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	int updateByExample(@Param("record") GatefireLEvento record, @Param("example") GatefireLEventoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	int updateByPrimaryKeySelective(GatefireLEvento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	int updateByPrimaryKey(GatefireLEvento record);

	@Select("select distinct codice_fiscale from gatefire.gatefire_l_evento where codice_fiscale like #{value}")
	List<String> selectCodiciFiscali(String part);
}