package it.csi.gatefire.dbhelper.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import it.csi.gatefire.dbhelper.model.GatefireDApplicazione;
import it.csi.gatefire.dbhelper.model.GatefireDApplicazioneExample;

public interface GatefireDApplicazioneMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	long countByExample(GatefireDApplicazioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	int deleteByExample(GatefireDApplicazioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	int deleteByPrimaryKey(String codice);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	int insert(GatefireDApplicazione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	int insertSelective(GatefireDApplicazione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	List<GatefireDApplicazione> selectByExample(GatefireDApplicazioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	GatefireDApplicazione selectByPrimaryKey(String codice);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	int updateByExampleSelective(@Param("record") GatefireDApplicazione record,
			@Param("example") GatefireDApplicazioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	int updateByExample(@Param("record") GatefireDApplicazione record,
			@Param("example") GatefireDApplicazioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	int updateByPrimaryKeySelective(GatefireDApplicazione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	int updateByPrimaryKey(GatefireDApplicazione record);
}