package it.csi.gatefire.dbhelper.dao;

import it.csi.gatefire.dbhelper.model.GatefireDXdscode;
import it.csi.gatefire.dbhelper.model.GatefireDXdscodeExample;
import it.csi.gatefire.dbhelper.model.GatefireDXdscodeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GatefireDXdscodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_xdscode
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    long countByExample(GatefireDXdscodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_xdscode
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    int deleteByExample(GatefireDXdscodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_xdscode
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    int deleteByPrimaryKey(GatefireDXdscodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_xdscode
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    int insert(GatefireDXdscode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_xdscode
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    int insertSelective(GatefireDXdscode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_xdscode
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    List<GatefireDXdscode> selectByExample(GatefireDXdscodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_xdscode
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    GatefireDXdscode selectByPrimaryKey(GatefireDXdscodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_xdscode
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    int updateByExampleSelective(@Param("record") GatefireDXdscode record, @Param("example") GatefireDXdscodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_xdscode
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    int updateByExample(@Param("record") GatefireDXdscode record, @Param("example") GatefireDXdscodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_xdscode
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    int updateByPrimaryKeySelective(GatefireDXdscode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_xdscode
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    int updateByPrimaryKey(GatefireDXdscode record);
}