package it.csi.gatefire.dbhelper.dao;

import it.csi.gatefire.dbhelper.model.GatefireRRepositoryAccount;
import it.csi.gatefire.dbhelper.model.GatefireRRepositoryAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GatefireRRepositoryAccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_account
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	long countByExample(GatefireRRepositoryAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_account
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	int deleteByExample(GatefireRRepositoryAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_account
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_account
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	int insert(GatefireRRepositoryAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_account
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	int insertSelective(GatefireRRepositoryAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_account
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	List<GatefireRRepositoryAccount> selectByExample(GatefireRRepositoryAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_account
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	GatefireRRepositoryAccount selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_account
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	int updateByExampleSelective(@Param("record") GatefireRRepositoryAccount record,
			@Param("example") GatefireRRepositoryAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_account
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	int updateByExample(@Param("record") GatefireRRepositoryAccount record,
			@Param("example") GatefireRRepositoryAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_account
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	int updateByPrimaryKeySelective(GatefireRRepositoryAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_account
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	int updateByPrimaryKey(GatefireRRepositoryAccount record);
}