/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gatefire.dbhelper.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import it.csi.gatefire.dbhelper.model.GatefireREventoEventoPadre;
import it.csi.gatefire.dbhelper.model.GatefireREventoEventoPadreExample;
import it.csi.gatefire.dbhelper.model.GatefireREventoEventoPadreKey;

public interface GatefireREventoEventoPadreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_evento_evento_padre
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    long countByExample(GatefireREventoEventoPadreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_evento_evento_padre
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int deleteByExample(GatefireREventoEventoPadreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_evento_evento_padre
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int deleteByPrimaryKey(GatefireREventoEventoPadreKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_evento_evento_padre
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int insert(GatefireREventoEventoPadre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_evento_evento_padre
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int insertSelective(GatefireREventoEventoPadre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_evento_evento_padre
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    List<GatefireREventoEventoPadre> selectByExample(GatefireREventoEventoPadreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_evento_evento_padre
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    GatefireREventoEventoPadre selectByPrimaryKey(GatefireREventoEventoPadreKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_evento_evento_padre
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int updateByExampleSelective(@Param("record") GatefireREventoEventoPadre record, @Param("example") GatefireREventoEventoPadreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_evento_evento_padre
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int updateByExample(@Param("record") GatefireREventoEventoPadre record, @Param("example") GatefireREventoEventoPadreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_evento_evento_padre
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int updateByPrimaryKeySelective(GatefireREventoEventoPadre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_r_evento_evento_padre
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    int updateByPrimaryKey(GatefireREventoEventoPadre record);
}