package it.csi.gatefire.dbhelper.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import it.csi.gatefire.dbhelper.model.GatefireRFunzioneApplicazione;
import it.csi.gatefire.dbhelper.model.GatefireRFunzioneApplicazioneExample;

public interface GatefireRFunzioneApplicazioneMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_funzione_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	long countByExample(GatefireRFunzioneApplicazioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_funzione_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	int deleteByExample(GatefireRFunzioneApplicazioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_funzione_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_funzione_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	int insert(GatefireRFunzioneApplicazione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_funzione_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	int insertSelective(GatefireRFunzioneApplicazione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_funzione_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	List<GatefireRFunzioneApplicazione> selectByExample(GatefireRFunzioneApplicazioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_funzione_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	GatefireRFunzioneApplicazione selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_funzione_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	int updateByExampleSelective(@Param("record") GatefireRFunzioneApplicazione record,
			@Param("example") GatefireRFunzioneApplicazioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_funzione_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	int updateByExample(@Param("record") GatefireRFunzioneApplicazione record,
			@Param("example") GatefireRFunzioneApplicazioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_funzione_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	int updateByPrimaryKeySelective(GatefireRFunzioneApplicazione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_funzione_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	int updateByPrimaryKey(GatefireRFunzioneApplicazione record);
}