package it.csi.gatefire.dbhelper.dao;

import it.csi.gatefire.dbhelper.model.GatefireRRepositoryUri;
import it.csi.gatefire.dbhelper.model.GatefireRRepositoryUriExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GatefireRRepositoryUriMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_uri
	 * @mbg.generated  Wed Apr 13 14:49:35 CEST 2022
	 */
	long countByExample(GatefireRRepositoryUriExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_uri
	 * @mbg.generated  Wed Apr 13 14:49:35 CEST 2022
	 */
	int deleteByExample(GatefireRRepositoryUriExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_uri
	 * @mbg.generated  Wed Apr 13 14:49:35 CEST 2022
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_uri
	 * @mbg.generated  Wed Apr 13 14:49:35 CEST 2022
	 */
	int insert(GatefireRRepositoryUri record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_uri
	 * @mbg.generated  Wed Apr 13 14:49:35 CEST 2022
	 */
	int insertSelective(GatefireRRepositoryUri record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_uri
	 * @mbg.generated  Wed Apr 13 14:49:35 CEST 2022
	 */
	List<GatefireRRepositoryUri> selectByExample(GatefireRRepositoryUriExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_uri
	 * @mbg.generated  Wed Apr 13 14:49:35 CEST 2022
	 */
	GatefireRRepositoryUri selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_uri
	 * @mbg.generated  Wed Apr 13 14:49:35 CEST 2022
	 */
	int updateByExampleSelective(@Param("record") GatefireRRepositoryUri record,
			@Param("example") GatefireRRepositoryUriExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_uri
	 * @mbg.generated  Wed Apr 13 14:49:35 CEST 2022
	 */
	int updateByExample(@Param("record") GatefireRRepositoryUri record,
			@Param("example") GatefireRRepositoryUriExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_uri
	 * @mbg.generated  Wed Apr 13 14:49:35 CEST 2022
	 */
	int updateByPrimaryKeySelective(GatefireRRepositoryUri record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_repository_uri
	 * @mbg.generated  Wed Apr 13 14:49:35 CEST 2022
	 */
	int updateByPrimaryKey(GatefireRRepositoryUri record);
}