/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gatefire.dbhelper.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import it.csi.gatefire.dbhelper.model.GatefireTAmministratore;
import it.csi.gatefire.dbhelper.model.GatefireTAmministratoreExample;

public interface GatefireTAmministratoreMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_amministratore
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	long countByExample(GatefireTAmministratoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_amministratore
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	int deleteByExample(GatefireTAmministratoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_amministratore
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_amministratore
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	int insert(GatefireTAmministratore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_amministratore
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	int insertSelective(GatefireTAmministratore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_amministratore
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	List<GatefireTAmministratore> selectByExample(GatefireTAmministratoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_amministratore
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	GatefireTAmministratore selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_amministratore
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	int updateByExampleSelective(@Param("record") GatefireTAmministratore record,
			@Param("example") GatefireTAmministratoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_amministratore
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	int updateByExample(@Param("record") GatefireTAmministratore record,
			@Param("example") GatefireTAmministratoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_amministratore
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	int updateByPrimaryKeySelective(GatefireTAmministratore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_amministratore
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	int updateByPrimaryKey(GatefireTAmministratore record);
}