package it.csi.gatefire.dbhelper.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import it.csi.gatefire.dbhelper.model.GatefireRAmministratoreRuolo;
import it.csi.gatefire.dbhelper.model.GatefireRAmministratoreRuoloExample;
import it.csi.gatefire.dbhelper.model.GatefireRAmministratoreRuoloKey;

public interface GatefireRAmministratoreRuoloMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_amministratore_ruolo
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	long countByExample(GatefireRAmministratoreRuoloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_amministratore_ruolo
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	int deleteByExample(GatefireRAmministratoreRuoloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_amministratore_ruolo
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	int deleteByPrimaryKey(GatefireRAmministratoreRuoloKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_amministratore_ruolo
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	int insert(GatefireRAmministratoreRuolo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_amministratore_ruolo
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	int insertSelective(GatefireRAmministratoreRuolo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_amministratore_ruolo
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	List<GatefireRAmministratoreRuolo> selectByExample(GatefireRAmministratoreRuoloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_amministratore_ruolo
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	GatefireRAmministratoreRuolo selectByPrimaryKey(GatefireRAmministratoreRuoloKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_amministratore_ruolo
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	int updateByExampleSelective(@Param("record") GatefireRAmministratoreRuolo record,
			@Param("example") GatefireRAmministratoreRuoloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_amministratore_ruolo
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	int updateByExample(@Param("record") GatefireRAmministratoreRuolo record,
			@Param("example") GatefireRAmministratoreRuoloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_amministratore_ruolo
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	int updateByPrimaryKeySelective(GatefireRAmministratoreRuolo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_r_amministratore_ruolo
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	int updateByPrimaryKey(GatefireRAmministratoreRuolo record);
}