/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gatefire.dbhelper.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import it.csi.gatefire.dbhelper.model.GatefireTRuolo;
import it.csi.gatefire.dbhelper.model.GatefireTRuoloExample;

public interface GatefireTRuoloMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_ruolo
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	long countByExample(GatefireTRuoloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_ruolo
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	int deleteByExample(GatefireTRuoloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_ruolo
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	int deleteByPrimaryKey(String codice);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_ruolo
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	int insert(GatefireTRuolo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_ruolo
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	int insertSelective(GatefireTRuolo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_ruolo
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	List<GatefireTRuolo> selectByExample(GatefireTRuoloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_ruolo
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	GatefireTRuolo selectByPrimaryKey(String codice);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_ruolo
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	int updateByExampleSelective(@Param("record") GatefireTRuolo record,
			@Param("example") GatefireTRuoloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_ruolo
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	int updateByExample(@Param("record") GatefireTRuolo record, @Param("example") GatefireTRuoloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_ruolo
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	int updateByPrimaryKeySelective(GatefireTRuolo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_t_ruolo
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	int updateByPrimaryKey(GatefireTRuolo record);

	List<GatefireTRuolo> getRuoliAmministratore(String username);
}