package it.csi.gatefire.dbhelper.dao;

import it.csi.gatefire.dbhelper.model.GatefireDCaCollocazioneDominio;
import it.csi.gatefire.dbhelper.model.GatefireDCaCollocazioneDominioExample;
import it.csi.gatefire.dbhelper.model.GatefireDCaCollocazioneDominioKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface GatefireDCaCollocazioneDominioMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_ca_collocazione_dominio
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	long countByExample(GatefireDCaCollocazioneDominioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_ca_collocazione_dominio
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	int deleteByExample(GatefireDCaCollocazioneDominioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_ca_collocazione_dominio
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	int deleteByPrimaryKey(GatefireDCaCollocazioneDominioKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_ca_collocazione_dominio
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	int insert(GatefireDCaCollocazioneDominio record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_ca_collocazione_dominio
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	int insertSelective(GatefireDCaCollocazioneDominio record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_ca_collocazione_dominio
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	List<GatefireDCaCollocazioneDominio> selectByExample(GatefireDCaCollocazioneDominioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_ca_collocazione_dominio
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	GatefireDCaCollocazioneDominio selectByPrimaryKey(GatefireDCaCollocazioneDominioKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_ca_collocazione_dominio
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	int updateByExampleSelective(@Param("record") GatefireDCaCollocazioneDominio record,
			@Param("example") GatefireDCaCollocazioneDominioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_ca_collocazione_dominio
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	int updateByExample(@Param("record") GatefireDCaCollocazioneDominio record,
			@Param("example") GatefireDCaCollocazioneDominioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_ca_collocazione_dominio
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	int updateByPrimaryKeySelective(GatefireDCaCollocazioneDominio record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_ca_collocazione_dominio
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	int updateByPrimaryKey(GatefireDCaCollocazioneDominio record);
	
	
	@Select("select distinct collocazione from gatefire.gatefire_d_ca_collocazione_dominio order by collocazione")
	List<String> getAllCollocazioni();
}