package it.csi.gatefire.dbhelper.model;

public class GatefireRAmministratoreRuoloKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_r_amministratore_ruolo.id_amministratore
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	private Integer idAmministratore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_r_amministratore_ruolo.codice_ruolo
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	private String codiceRuolo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_r_amministratore_ruolo.id_amministratore
	 * @return  the value of gatefire.gatefire_r_amministratore_ruolo.id_amministratore
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	public Integer getIdAmministratore() {
		return idAmministratore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_r_amministratore_ruolo.id_amministratore
	 * @param idAmministratore  the value for gatefire.gatefire_r_amministratore_ruolo.id_amministratore
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	public void setIdAmministratore(Integer idAmministratore) {
		this.idAmministratore = idAmministratore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_r_amministratore_ruolo.codice_ruolo
	 * @return  the value of gatefire.gatefire_r_amministratore_ruolo.codice_ruolo
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	public String getCodiceRuolo() {
		return codiceRuolo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_r_amministratore_ruolo.codice_ruolo
	 * @param codiceRuolo  the value for gatefire.gatefire_r_amministratore_ruolo.codice_ruolo
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	public void setCodiceRuolo(String codiceRuolo) {
		this.codiceRuolo = codiceRuolo;
	}
}