/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gatefire.dbhelper.model;

import java.util.Date;

public class GatefireRRepositoryAccount {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_r_repository_account.id
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_r_repository_account.codice_repository
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	private String codiceRepository;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_r_repository_account.codice_applicazione
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	private String codiceApplicazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_r_repository_account.username
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_r_repository_account.hashed_password
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	private String hashedPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_r_repository_account.salt
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	private String salt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_r_repository_account.data_inizio_validita
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	private Date dataInizioValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_r_repository_account.data_fine_validita
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	private Date dataFineValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_r_repository_account.data_creazione
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_r_repository_account.data_aggiornamento
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	private Date dataAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_r_repository_account.data_cancellazione
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_r_repository_account.id
	 * @return  the value of gatefire.gatefire_r_repository_account.id
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_r_repository_account.id
	 * @param id  the value for gatefire.gatefire_r_repository_account.id
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_r_repository_account.codice_repository
	 * @return  the value of gatefire.gatefire_r_repository_account.codice_repository
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public String getCodiceRepository() {
		return codiceRepository;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_r_repository_account.codice_repository
	 * @param codiceRepository  the value for gatefire.gatefire_r_repository_account.codice_repository
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public void setCodiceRepository(String codiceRepository) {
		this.codiceRepository = codiceRepository;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_r_repository_account.codice_applicazione
	 * @return  the value of gatefire.gatefire_r_repository_account.codice_applicazione
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public String getCodiceApplicazione() {
		return codiceApplicazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_r_repository_account.codice_applicazione
	 * @param codiceApplicazione  the value for gatefire.gatefire_r_repository_account.codice_applicazione
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public void setCodiceApplicazione(String codiceApplicazione) {
		this.codiceApplicazione = codiceApplicazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_r_repository_account.username
	 * @return  the value of gatefire.gatefire_r_repository_account.username
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_r_repository_account.username
	 * @param username  the value for gatefire.gatefire_r_repository_account.username
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_r_repository_account.hashed_password
	 * @return  the value of gatefire.gatefire_r_repository_account.hashed_password
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public String getHashedPassword() {
		return hashedPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_r_repository_account.hashed_password
	 * @param hashedPassword  the value for gatefire.gatefire_r_repository_account.hashed_password
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public void setHashedPassword(String hashedPassword) {
		this.hashedPassword = hashedPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_r_repository_account.salt
	 * @return  the value of gatefire.gatefire_r_repository_account.salt
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_r_repository_account.salt
	 * @param salt  the value for gatefire.gatefire_r_repository_account.salt
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public void setSalt(String salt) {
		this.salt = salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_r_repository_account.data_inizio_validita
	 * @return  the value of gatefire.gatefire_r_repository_account.data_inizio_validita
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public Date getDataInizioValidita() {
		return dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_r_repository_account.data_inizio_validita
	 * @param dataInizioValidita  the value for gatefire.gatefire_r_repository_account.data_inizio_validita
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public void setDataInizioValidita(Date dataInizioValidita) {
		this.dataInizioValidita = dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_r_repository_account.data_fine_validita
	 * @return  the value of gatefire.gatefire_r_repository_account.data_fine_validita
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public Date getDataFineValidita() {
		return dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_r_repository_account.data_fine_validita
	 * @param dataFineValidita  the value for gatefire.gatefire_r_repository_account.data_fine_validita
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public void setDataFineValidita(Date dataFineValidita) {
		this.dataFineValidita = dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_r_repository_account.data_creazione
	 * @return  the value of gatefire.gatefire_r_repository_account.data_creazione
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_r_repository_account.data_creazione
	 * @param dataCreazione  the value for gatefire.gatefire_r_repository_account.data_creazione
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_r_repository_account.data_aggiornamento
	 * @return  the value of gatefire.gatefire_r_repository_account.data_aggiornamento
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_r_repository_account.data_aggiornamento
	 * @param dataAggiornamento  the value for gatefire.gatefire_r_repository_account.data_aggiornamento
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_r_repository_account.data_cancellazione
	 * @return  the value of gatefire.gatefire_r_repository_account.data_cancellazione
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_r_repository_account.data_cancellazione
	 * @param dataCancellazione  the value for gatefire.gatefire_r_repository_account.data_cancellazione
	 * @mbg.generated  Fri Jun 24 12:23:36 CEST 2022
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}