/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gatefire.dbhelper.model;

import java.util.Date;

public class GatefireRRepositoryFunzione {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gatefire.gatefire_r_repository_funzione.id
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gatefire.gatefire_r_repository_funzione.codice_repository
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    private String codiceRepository;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gatefire.gatefire_r_repository_funzione.codice_funzione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    private String codiceFunzione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gatefire.gatefire_r_repository_funzione.data_inizio_validita
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    private Date dataInizioValidita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gatefire.gatefire_r_repository_funzione.data_fine_validita
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    private Date dataFineValidita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gatefire.gatefire_r_repository_funzione.data_creazione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    private Date dataCreazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gatefire.gatefire_r_repository_funzione.data_aggiornamento
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    private Date dataAggiornamento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gatefire.gatefire_r_repository_funzione.data_cancellazione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    private Date dataCancellazione;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gatefire.gatefire_r_repository_funzione.id
     *
     * @return the value of gatefire.gatefire_r_repository_funzione.id
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gatefire.gatefire_r_repository_funzione.id
     *
     * @param id the value for gatefire.gatefire_r_repository_funzione.id
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gatefire.gatefire_r_repository_funzione.codice_repository
     *
     * @return the value of gatefire.gatefire_r_repository_funzione.codice_repository
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public String getCodiceRepository() {
        return codiceRepository;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gatefire.gatefire_r_repository_funzione.codice_repository
     *
     * @param codiceRepository the value for gatefire.gatefire_r_repository_funzione.codice_repository
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public void setCodiceRepository(String codiceRepository) {
        this.codiceRepository = codiceRepository;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gatefire.gatefire_r_repository_funzione.codice_funzione
     *
     * @return the value of gatefire.gatefire_r_repository_funzione.codice_funzione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public String getCodiceFunzione() {
        return codiceFunzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gatefire.gatefire_r_repository_funzione.codice_funzione
     *
     * @param codiceFunzione the value for gatefire.gatefire_r_repository_funzione.codice_funzione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public void setCodiceFunzione(String codiceFunzione) {
        this.codiceFunzione = codiceFunzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gatefire.gatefire_r_repository_funzione.data_inizio_validita
     *
     * @return the value of gatefire.gatefire_r_repository_funzione.data_inizio_validita
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public Date getDataInizioValidita() {
        return dataInizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gatefire.gatefire_r_repository_funzione.data_inizio_validita
     *
     * @param dataInizioValidita the value for gatefire.gatefire_r_repository_funzione.data_inizio_validita
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public void setDataInizioValidita(Date dataInizioValidita) {
        this.dataInizioValidita = dataInizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gatefire.gatefire_r_repository_funzione.data_fine_validita
     *
     * @return the value of gatefire.gatefire_r_repository_funzione.data_fine_validita
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public Date getDataFineValidita() {
        return dataFineValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gatefire.gatefire_r_repository_funzione.data_fine_validita
     *
     * @param dataFineValidita the value for gatefire.gatefire_r_repository_funzione.data_fine_validita
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public void setDataFineValidita(Date dataFineValidita) {
        this.dataFineValidita = dataFineValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gatefire.gatefire_r_repository_funzione.data_creazione
     *
     * @return the value of gatefire.gatefire_r_repository_funzione.data_creazione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public Date getDataCreazione() {
        return dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gatefire.gatefire_r_repository_funzione.data_creazione
     *
     * @param dataCreazione the value for gatefire.gatefire_r_repository_funzione.data_creazione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gatefire.gatefire_r_repository_funzione.data_aggiornamento
     *
     * @return the value of gatefire.gatefire_r_repository_funzione.data_aggiornamento
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public Date getDataAggiornamento() {
        return dataAggiornamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gatefire.gatefire_r_repository_funzione.data_aggiornamento
     *
     * @param dataAggiornamento the value for gatefire.gatefire_r_repository_funzione.data_aggiornamento
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public void setDataAggiornamento(Date dataAggiornamento) {
        this.dataAggiornamento = dataAggiornamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gatefire.gatefire_r_repository_funzione.data_cancellazione
     *
     * @return the value of gatefire.gatefire_r_repository_funzione.data_cancellazione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public Date getDataCancellazione() {
        return dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gatefire.gatefire_r_repository_funzione.data_cancellazione
     *
     * @param dataCancellazione the value for gatefire.gatefire_r_repository_funzione.data_cancellazione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public void setDataCancellazione(Date dataCancellazione) {
        this.dataCancellazione = dataCancellazione;
    }
}