/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gatefire.dbhelper.model;

public class GatefireDXdscode extends GatefireDXdscodeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gatefire.gatefire_d_xdscode.coding_scheme
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    private String codingScheme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gatefire.gatefire_d_xdscode.display_name
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    private String displayName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gatefire.gatefire_d_xdscode.coding_scheme
     *
     * @return the value of gatefire.gatefire_d_xdscode.coding_scheme
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    public String getCodingScheme() {
        return codingScheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gatefire.gatefire_d_xdscode.coding_scheme
     *
     * @param codingScheme the value for gatefire.gatefire_d_xdscode.coding_scheme
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    public void setCodingScheme(String codingScheme) {
        this.codingScheme = codingScheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gatefire.gatefire_d_xdscode.display_name
     *
     * @return the value of gatefire.gatefire_d_xdscode.display_name
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gatefire.gatefire_d_xdscode.display_name
     *
     * @param displayName the value for gatefire.gatefire_d_xdscode.display_name
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
}