package it.csi.gatefire.dbhelper.model;

import java.util.Date;

public class GatefireRAmministratoreRuolo extends GatefireRAmministratoreRuoloKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_r_amministratore_ruolo.data_fine_validita
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	private Date dataFineValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_r_amministratore_ruolo.data_creazione
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_r_amministratore_ruolo.data_aggiornamento
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	private Date dataAggiornamento;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_r_amministratore_ruolo.data_fine_validita
	 * @return  the value of gatefire.gatefire_r_amministratore_ruolo.data_fine_validita
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	public Date getDataFineValidita() {
		return dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_r_amministratore_ruolo.data_fine_validita
	 * @param dataFineValidita  the value for gatefire.gatefire_r_amministratore_ruolo.data_fine_validita
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	public void setDataFineValidita(Date dataFineValidita) {
		this.dataFineValidita = dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_r_amministratore_ruolo.data_creazione
	 * @return  the value of gatefire.gatefire_r_amministratore_ruolo.data_creazione
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_r_amministratore_ruolo.data_creazione
	 * @param dataCreazione  the value for gatefire.gatefire_r_amministratore_ruolo.data_creazione
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_r_amministratore_ruolo.data_aggiornamento
	 * @return  the value of gatefire.gatefire_r_amministratore_ruolo.data_aggiornamento
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_r_amministratore_ruolo.data_aggiornamento
	 * @param dataAggiornamento  the value for gatefire.gatefire_r_amministratore_ruolo.data_aggiornamento
	 * @mbg.generated  Tue Sep 29 15:05:27 CEST 2020
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}
}