/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gatefire.dbhelper.model;

public class GatefireDXdscodeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gatefire.gatefire_d_xdscode.code_type
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    private String codeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gatefire.gatefire_d_xdscode.code
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gatefire.gatefire_d_xdscode.code_type
     *
     * @return the value of gatefire.gatefire_d_xdscode.code_type
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    public String getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gatefire.gatefire_d_xdscode.code_type
     *
     * @param codeType the value for gatefire.gatefire_d_xdscode.code_type
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    public void setCodeType(String codeType) {
        this.codeType = codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gatefire.gatefire_d_xdscode.code
     *
     * @return the value of gatefire.gatefire_d_xdscode.code
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gatefire.gatefire_d_xdscode.code
     *
     * @param code the value for gatefire.gatefire_d_xdscode.code
     *
     * @mbg.generated Mon Jan 10 12:19:16 CET 2022
     */
    public void setCode(String code) {
        this.code = code;
    }
}