/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gatefire.dbhelper.model;

import java.util.Date;

public class GatefireDParametro {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_parametro.parametro
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private String parametro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_parametro.descrizione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private String descrizione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_parametro.tipo_parametro
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private String tipoParametro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_parametro.uso_parametro
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private String usoParametro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_parametro.tag_ca
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private String tagCa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_parametro.data_inizio_validita
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private Date dataInizioValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_parametro.data_fine_validita
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private Date dataFineValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_parametro.data_creazione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_parametro.data_aggiornamento
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private Date dataAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_parametro.data_cancellazione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_parametro.parametro
	 * @return  the value of gatefire.gatefire_d_parametro.parametro
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public String getParametro() {
		return parametro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_parametro.parametro
	 * @param parametro  the value for gatefire.gatefire_d_parametro.parametro
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setParametro(String parametro) {
		this.parametro = parametro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_parametro.descrizione
	 * @return  the value of gatefire.gatefire_d_parametro.descrizione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public String getDescrizione() {
		return descrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_parametro.descrizione
	 * @param descrizione  the value for gatefire.gatefire_d_parametro.descrizione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_parametro.tipo_parametro
	 * @return  the value of gatefire.gatefire_d_parametro.tipo_parametro
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public String getTipoParametro() {
		return tipoParametro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_parametro.tipo_parametro
	 * @param tipoParametro  the value for gatefire.gatefire_d_parametro.tipo_parametro
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setTipoParametro(String tipoParametro) {
		this.tipoParametro = tipoParametro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_parametro.uso_parametro
	 * @return  the value of gatefire.gatefire_d_parametro.uso_parametro
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public String getUsoParametro() {
		return usoParametro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_parametro.uso_parametro
	 * @param usoParametro  the value for gatefire.gatefire_d_parametro.uso_parametro
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setUsoParametro(String usoParametro) {
		this.usoParametro = usoParametro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_parametro.tag_ca
	 * @return  the value of gatefire.gatefire_d_parametro.tag_ca
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public String getTagCa() {
		return tagCa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_parametro.tag_ca
	 * @param tagCa  the value for gatefire.gatefire_d_parametro.tag_ca
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setTagCa(String tagCa) {
		this.tagCa = tagCa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_parametro.data_inizio_validita
	 * @return  the value of gatefire.gatefire_d_parametro.data_inizio_validita
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public Date getDataInizioValidita() {
		return dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_parametro.data_inizio_validita
	 * @param dataInizioValidita  the value for gatefire.gatefire_d_parametro.data_inizio_validita
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setDataInizioValidita(Date dataInizioValidita) {
		this.dataInizioValidita = dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_parametro.data_fine_validita
	 * @return  the value of gatefire.gatefire_d_parametro.data_fine_validita
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public Date getDataFineValidita() {
		return dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_parametro.data_fine_validita
	 * @param dataFineValidita  the value for gatefire.gatefire_d_parametro.data_fine_validita
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setDataFineValidita(Date dataFineValidita) {
		this.dataFineValidita = dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_parametro.data_creazione
	 * @return  the value of gatefire.gatefire_d_parametro.data_creazione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_parametro.data_creazione
	 * @param dataCreazione  the value for gatefire.gatefire_d_parametro.data_creazione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_parametro.data_aggiornamento
	 * @return  the value of gatefire.gatefire_d_parametro.data_aggiornamento
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_parametro.data_aggiornamento
	 * @param dataAggiornamento  the value for gatefire.gatefire_d_parametro.data_aggiornamento
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_parametro.data_cancellazione
	 * @return  the value of gatefire.gatefire_d_parametro.data_cancellazione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_parametro.data_cancellazione
	 * @param dataCancellazione  the value for gatefire.gatefire_d_parametro.data_cancellazione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}