package it.csi.gatefire.dbhelper.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GatefireLEventoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public GatefireLEventoExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andDataInizioElabIsNull() {
			addCriterion("data_inizio_elab is null");
			return (Criteria) this;
		}

		public Criteria andDataInizioElabIsNotNull() {
			addCriterion("data_inizio_elab is not null");
			return (Criteria) this;
		}

		public Criteria andDataInizioElabEqualTo(Date value) {
			addCriterion("data_inizio_elab =", value, "dataInizioElab");
			return (Criteria) this;
		}

		public Criteria andDataInizioElabNotEqualTo(Date value) {
			addCriterion("data_inizio_elab <>", value, "dataInizioElab");
			return (Criteria) this;
		}

		public Criteria andDataInizioElabGreaterThan(Date value) {
			addCriterion("data_inizio_elab >", value, "dataInizioElab");
			return (Criteria) this;
		}

		public Criteria andDataInizioElabGreaterThanOrEqualTo(Date value) {
			addCriterion("data_inizio_elab >=", value, "dataInizioElab");
			return (Criteria) this;
		}

		public Criteria andDataInizioElabLessThan(Date value) {
			addCriterion("data_inizio_elab <", value, "dataInizioElab");
			return (Criteria) this;
		}

		public Criteria andDataInizioElabLessThanOrEqualTo(Date value) {
			addCriterion("data_inizio_elab <=", value, "dataInizioElab");
			return (Criteria) this;
		}

		public Criteria andDataInizioElabIn(List<Date> values) {
			addCriterion("data_inizio_elab in", values, "dataInizioElab");
			return (Criteria) this;
		}

		public Criteria andDataInizioElabNotIn(List<Date> values) {
			addCriterion("data_inizio_elab not in", values, "dataInizioElab");
			return (Criteria) this;
		}

		public Criteria andDataInizioElabBetween(Date value1, Date value2) {
			addCriterion("data_inizio_elab between", value1, value2, "dataInizioElab");
			return (Criteria) this;
		}

		public Criteria andDataInizioElabNotBetween(Date value1, Date value2) {
			addCriterion("data_inizio_elab not between", value1, value2, "dataInizioElab");
			return (Criteria) this;
		}

		public Criteria andDataFineElabIsNull() {
			addCriterion("data_fine_elab is null");
			return (Criteria) this;
		}

		public Criteria andDataFineElabIsNotNull() {
			addCriterion("data_fine_elab is not null");
			return (Criteria) this;
		}

		public Criteria andDataFineElabEqualTo(Date value) {
			addCriterion("data_fine_elab =", value, "dataFineElab");
			return (Criteria) this;
		}

		public Criteria andDataFineElabNotEqualTo(Date value) {
			addCriterion("data_fine_elab <>", value, "dataFineElab");
			return (Criteria) this;
		}

		public Criteria andDataFineElabGreaterThan(Date value) {
			addCriterion("data_fine_elab >", value, "dataFineElab");
			return (Criteria) this;
		}

		public Criteria andDataFineElabGreaterThanOrEqualTo(Date value) {
			addCriterion("data_fine_elab >=", value, "dataFineElab");
			return (Criteria) this;
		}

		public Criteria andDataFineElabLessThan(Date value) {
			addCriterion("data_fine_elab <", value, "dataFineElab");
			return (Criteria) this;
		}

		public Criteria andDataFineElabLessThanOrEqualTo(Date value) {
			addCriterion("data_fine_elab <=", value, "dataFineElab");
			return (Criteria) this;
		}

		public Criteria andDataFineElabIn(List<Date> values) {
			addCriterion("data_fine_elab in", values, "dataFineElab");
			return (Criteria) this;
		}

		public Criteria andDataFineElabNotIn(List<Date> values) {
			addCriterion("data_fine_elab not in", values, "dataFineElab");
			return (Criteria) this;
		}

		public Criteria andDataFineElabBetween(Date value1, Date value2) {
			addCriterion("data_fine_elab between", value1, value2, "dataFineElab");
			return (Criteria) this;
		}

		public Criteria andDataFineElabNotBetween(Date value1, Date value2) {
			addCriterion("data_fine_elab not between", value1, value2, "dataFineElab");
			return (Criteria) this;
		}

		public Criteria andDataAggStatoIsNull() {
			addCriterion("data_agg_stato is null");
			return (Criteria) this;
		}

		public Criteria andDataAggStatoIsNotNull() {
			addCriterion("data_agg_stato is not null");
			return (Criteria) this;
		}

		public Criteria andDataAggStatoEqualTo(Date value) {
			addCriterion("data_agg_stato =", value, "dataAggStato");
			return (Criteria) this;
		}

		public Criteria andDataAggStatoNotEqualTo(Date value) {
			addCriterion("data_agg_stato <>", value, "dataAggStato");
			return (Criteria) this;
		}

		public Criteria andDataAggStatoGreaterThan(Date value) {
			addCriterion("data_agg_stato >", value, "dataAggStato");
			return (Criteria) this;
		}

		public Criteria andDataAggStatoGreaterThanOrEqualTo(Date value) {
			addCriterion("data_agg_stato >=", value, "dataAggStato");
			return (Criteria) this;
		}

		public Criteria andDataAggStatoLessThan(Date value) {
			addCriterion("data_agg_stato <", value, "dataAggStato");
			return (Criteria) this;
		}

		public Criteria andDataAggStatoLessThanOrEqualTo(Date value) {
			addCriterion("data_agg_stato <=", value, "dataAggStato");
			return (Criteria) this;
		}

		public Criteria andDataAggStatoIn(List<Date> values) {
			addCriterion("data_agg_stato in", values, "dataAggStato");
			return (Criteria) this;
		}

		public Criteria andDataAggStatoNotIn(List<Date> values) {
			addCriterion("data_agg_stato not in", values, "dataAggStato");
			return (Criteria) this;
		}

		public Criteria andDataAggStatoBetween(Date value1, Date value2) {
			addCriterion("data_agg_stato between", value1, value2, "dataAggStato");
			return (Criteria) this;
		}

		public Criteria andDataAggStatoNotBetween(Date value1, Date value2) {
			addCriterion("data_agg_stato not between", value1, value2, "dataAggStato");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneIsNull() {
			addCriterion("data_creazione is null");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneIsNotNull() {
			addCriterion("data_creazione is not null");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneEqualTo(Date value) {
			addCriterion("data_creazione =", value, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneNotEqualTo(Date value) {
			addCriterion("data_creazione <>", value, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneGreaterThan(Date value) {
			addCriterion("data_creazione >", value, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneGreaterThanOrEqualTo(Date value) {
			addCriterion("data_creazione >=", value, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneLessThan(Date value) {
			addCriterion("data_creazione <", value, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneLessThanOrEqualTo(Date value) {
			addCriterion("data_creazione <=", value, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneIn(List<Date> values) {
			addCriterion("data_creazione in", values, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneNotIn(List<Date> values) {
			addCriterion("data_creazione not in", values, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneBetween(Date value1, Date value2) {
			addCriterion("data_creazione between", value1, value2, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneNotBetween(Date value1, Date value2) {
			addCriterion("data_creazione not between", value1, value2, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andIdUtenteIsNull() {
			addCriterion("id_utente is null");
			return (Criteria) this;
		}

		public Criteria andIdUtenteIsNotNull() {
			addCriterion("id_utente is not null");
			return (Criteria) this;
		}

		public Criteria andIdUtenteEqualTo(String value) {
			addCriterion("id_utente =", value, "idUtente");
			return (Criteria) this;
		}

		public Criteria andIdUtenteNotEqualTo(String value) {
			addCriterion("id_utente <>", value, "idUtente");
			return (Criteria) this;
		}

		public Criteria andIdUtenteGreaterThan(String value) {
			addCriterion("id_utente >", value, "idUtente");
			return (Criteria) this;
		}

		public Criteria andIdUtenteGreaterThanOrEqualTo(String value) {
			addCriterion("id_utente >=", value, "idUtente");
			return (Criteria) this;
		}

		public Criteria andIdUtenteLessThan(String value) {
			addCriterion("id_utente <", value, "idUtente");
			return (Criteria) this;
		}

		public Criteria andIdUtenteLessThanOrEqualTo(String value) {
			addCriterion("id_utente <=", value, "idUtente");
			return (Criteria) this;
		}

		public Criteria andIdUtenteLike(String value) {
			addCriterion("id_utente like", value, "idUtente");
			return (Criteria) this;
		}

		public Criteria andIdUtenteNotLike(String value) {
			addCriterion("id_utente not like", value, "idUtente");
			return (Criteria) this;
		}

		public Criteria andIdUtenteIn(List<String> values) {
			addCriterion("id_utente in", values, "idUtente");
			return (Criteria) this;
		}

		public Criteria andIdUtenteNotIn(List<String> values) {
			addCriterion("id_utente not in", values, "idUtente");
			return (Criteria) this;
		}

		public Criteria andIdUtenteBetween(String value1, String value2) {
			addCriterion("id_utente between", value1, value2, "idUtente");
			return (Criteria) this;
		}

		public Criteria andIdUtenteNotBetween(String value1, String value2) {
			addCriterion("id_utente not between", value1, value2, "idUtente");
			return (Criteria) this;
		}

		public Criteria andIdSessioneIsNull() {
			addCriterion("id_sessione is null");
			return (Criteria) this;
		}

		public Criteria andIdSessioneIsNotNull() {
			addCriterion("id_sessione is not null");
			return (Criteria) this;
		}

		public Criteria andIdSessioneEqualTo(String value) {
			addCriterion("id_sessione =", value, "idSessione");
			return (Criteria) this;
		}

		public Criteria andIdSessioneNotEqualTo(String value) {
			addCriterion("id_sessione <>", value, "idSessione");
			return (Criteria) this;
		}

		public Criteria andIdSessioneGreaterThan(String value) {
			addCriterion("id_sessione >", value, "idSessione");
			return (Criteria) this;
		}

		public Criteria andIdSessioneGreaterThanOrEqualTo(String value) {
			addCriterion("id_sessione >=", value, "idSessione");
			return (Criteria) this;
		}

		public Criteria andIdSessioneLessThan(String value) {
			addCriterion("id_sessione <", value, "idSessione");
			return (Criteria) this;
		}

		public Criteria andIdSessioneLessThanOrEqualTo(String value) {
			addCriterion("id_sessione <=", value, "idSessione");
			return (Criteria) this;
		}

		public Criteria andIdSessioneLike(String value) {
			addCriterion("id_sessione like", value, "idSessione");
			return (Criteria) this;
		}

		public Criteria andIdSessioneNotLike(String value) {
			addCriterion("id_sessione not like", value, "idSessione");
			return (Criteria) this;
		}

		public Criteria andIdSessioneIn(List<String> values) {
			addCriterion("id_sessione in", values, "idSessione");
			return (Criteria) this;
		}

		public Criteria andIdSessioneNotIn(List<String> values) {
			addCriterion("id_sessione not in", values, "idSessione");
			return (Criteria) this;
		}

		public Criteria andIdSessioneBetween(String value1, String value2) {
			addCriterion("id_sessione between", value1, value2, "idSessione");
			return (Criteria) this;
		}

		public Criteria andIdSessioneNotBetween(String value1, String value2) {
			addCriterion("id_sessione not between", value1, value2, "idSessione");
			return (Criteria) this;
		}

		public Criteria andCodiceFiscaleIsNull() {
			addCriterion("codice_fiscale is null");
			return (Criteria) this;
		}

		public Criteria andCodiceFiscaleIsNotNull() {
			addCriterion("codice_fiscale is not null");
			return (Criteria) this;
		}

		public Criteria andCodiceFiscaleEqualTo(String value) {
			addCriterion("codice_fiscale =", value, "codiceFiscale");
			return (Criteria) this;
		}

		public Criteria andCodiceFiscaleNotEqualTo(String value) {
			addCriterion("codice_fiscale <>", value, "codiceFiscale");
			return (Criteria) this;
		}

		public Criteria andCodiceFiscaleGreaterThan(String value) {
			addCriterion("codice_fiscale >", value, "codiceFiscale");
			return (Criteria) this;
		}

		public Criteria andCodiceFiscaleGreaterThanOrEqualTo(String value) {
			addCriterion("codice_fiscale >=", value, "codiceFiscale");
			return (Criteria) this;
		}

		public Criteria andCodiceFiscaleLessThan(String value) {
			addCriterion("codice_fiscale <", value, "codiceFiscale");
			return (Criteria) this;
		}

		public Criteria andCodiceFiscaleLessThanOrEqualTo(String value) {
			addCriterion("codice_fiscale <=", value, "codiceFiscale");
			return (Criteria) this;
		}

		public Criteria andCodiceFiscaleLike(String value) {
			addCriterion("codice_fiscale like", value, "codiceFiscale");
			return (Criteria) this;
		}

		public Criteria andCodiceFiscaleNotLike(String value) {
			addCriterion("codice_fiscale not like", value, "codiceFiscale");
			return (Criteria) this;
		}

		public Criteria andCodiceFiscaleIn(List<String> values) {
			addCriterion("codice_fiscale in", values, "codiceFiscale");
			return (Criteria) this;
		}

		public Criteria andCodiceFiscaleNotIn(List<String> values) {
			addCriterion("codice_fiscale not in", values, "codiceFiscale");
			return (Criteria) this;
		}

		public Criteria andCodiceFiscaleBetween(String value1, String value2) {
			addCriterion("codice_fiscale between", value1, value2, "codiceFiscale");
			return (Criteria) this;
		}

		public Criteria andCodiceFiscaleNotBetween(String value1, String value2) {
			addCriterion("codice_fiscale not between", value1, value2, "codiceFiscale");
			return (Criteria) this;
		}

		public Criteria andIpApplicazioneIsNull() {
			addCriterion("ip_applicazione is null");
			return (Criteria) this;
		}

		public Criteria andIpApplicazioneIsNotNull() {
			addCriterion("ip_applicazione is not null");
			return (Criteria) this;
		}

		public Criteria andIpApplicazioneEqualTo(String value) {
			addCriterion("ip_applicazione =", value, "ipApplicazione");
			return (Criteria) this;
		}

		public Criteria andIpApplicazioneNotEqualTo(String value) {
			addCriterion("ip_applicazione <>", value, "ipApplicazione");
			return (Criteria) this;
		}

		public Criteria andIpApplicazioneGreaterThan(String value) {
			addCriterion("ip_applicazione >", value, "ipApplicazione");
			return (Criteria) this;
		}

		public Criteria andIpApplicazioneGreaterThanOrEqualTo(String value) {
			addCriterion("ip_applicazione >=", value, "ipApplicazione");
			return (Criteria) this;
		}

		public Criteria andIpApplicazioneLessThan(String value) {
			addCriterion("ip_applicazione <", value, "ipApplicazione");
			return (Criteria) this;
		}

		public Criteria andIpApplicazioneLessThanOrEqualTo(String value) {
			addCriterion("ip_applicazione <=", value, "ipApplicazione");
			return (Criteria) this;
		}

		public Criteria andIpApplicazioneLike(String value) {
			addCriterion("ip_applicazione like", value, "ipApplicazione");
			return (Criteria) this;
		}

		public Criteria andIpApplicazioneNotLike(String value) {
			addCriterion("ip_applicazione not like", value, "ipApplicazione");
			return (Criteria) this;
		}

		public Criteria andIpApplicazioneIn(List<String> values) {
			addCriterion("ip_applicazione in", values, "ipApplicazione");
			return (Criteria) this;
		}

		public Criteria andIpApplicazioneNotIn(List<String> values) {
			addCriterion("ip_applicazione not in", values, "ipApplicazione");
			return (Criteria) this;
		}

		public Criteria andIpApplicazioneBetween(String value1, String value2) {
			addCriterion("ip_applicazione between", value1, value2, "ipApplicazione");
			return (Criteria) this;
		}

		public Criteria andIpApplicazioneNotBetween(String value1, String value2) {
			addCriterion("ip_applicazione not between", value1, value2, "ipApplicazione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneIsNull() {
			addCriterion("descrizione is null");
			return (Criteria) this;
		}

		public Criteria andDescrizioneIsNotNull() {
			addCriterion("descrizione is not null");
			return (Criteria) this;
		}

		public Criteria andDescrizioneEqualTo(String value) {
			addCriterion("descrizione =", value, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneNotEqualTo(String value) {
			addCriterion("descrizione <>", value, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneGreaterThan(String value) {
			addCriterion("descrizione >", value, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneGreaterThanOrEqualTo(String value) {
			addCriterion("descrizione >=", value, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneLessThan(String value) {
			addCriterion("descrizione <", value, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneLessThanOrEqualTo(String value) {
			addCriterion("descrizione <=", value, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneLike(String value) {
			addCriterion("descrizione like", value, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneNotLike(String value) {
			addCriterion("descrizione not like", value, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneIn(List<String> values) {
			addCriterion("descrizione in", values, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneNotIn(List<String> values) {
			addCriterion("descrizione not in", values, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneBetween(String value1, String value2) {
			addCriterion("descrizione between", value1, value2, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneNotBetween(String value1, String value2) {
			addCriterion("descrizione not between", value1, value2, "descrizione");
			return (Criteria) this;
		}

		public Criteria andNomeFileIsNull() {
			addCriterion("nome_file is null");
			return (Criteria) this;
		}

		public Criteria andNomeFileIsNotNull() {
			addCriterion("nome_file is not null");
			return (Criteria) this;
		}

		public Criteria andNomeFileEqualTo(String value) {
			addCriterion("nome_file =", value, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileNotEqualTo(String value) {
			addCriterion("nome_file <>", value, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileGreaterThan(String value) {
			addCriterion("nome_file >", value, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileGreaterThanOrEqualTo(String value) {
			addCriterion("nome_file >=", value, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileLessThan(String value) {
			addCriterion("nome_file <", value, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileLessThanOrEqualTo(String value) {
			addCriterion("nome_file <=", value, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileLike(String value) {
			addCriterion("nome_file like", value, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileNotLike(String value) {
			addCriterion("nome_file not like", value, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileIn(List<String> values) {
			addCriterion("nome_file in", values, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileNotIn(List<String> values) {
			addCriterion("nome_file not in", values, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileBetween(String value1, String value2) {
			addCriterion("nome_file between", value1, value2, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileNotBetween(String value1, String value2) {
			addCriterion("nome_file not between", value1, value2, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andCodiceStatoEventoIsNull() {
			addCriterion("codice_stato_evento is null");
			return (Criteria) this;
		}

		public Criteria andCodiceStatoEventoIsNotNull() {
			addCriterion("codice_stato_evento is not null");
			return (Criteria) this;
		}

		public Criteria andCodiceStatoEventoEqualTo(String value) {
			addCriterion("codice_stato_evento =", value, "codiceStatoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceStatoEventoNotEqualTo(String value) {
			addCriterion("codice_stato_evento <>", value, "codiceStatoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceStatoEventoGreaterThan(String value) {
			addCriterion("codice_stato_evento >", value, "codiceStatoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceStatoEventoGreaterThanOrEqualTo(String value) {
			addCriterion("codice_stato_evento >=", value, "codiceStatoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceStatoEventoLessThan(String value) {
			addCriterion("codice_stato_evento <", value, "codiceStatoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceStatoEventoLessThanOrEqualTo(String value) {
			addCriterion("codice_stato_evento <=", value, "codiceStatoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceStatoEventoLike(String value) {
			addCriterion("codice_stato_evento like", value, "codiceStatoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceStatoEventoNotLike(String value) {
			addCriterion("codice_stato_evento not like", value, "codiceStatoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceStatoEventoIn(List<String> values) {
			addCriterion("codice_stato_evento in", values, "codiceStatoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceStatoEventoNotIn(List<String> values) {
			addCriterion("codice_stato_evento not in", values, "codiceStatoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceStatoEventoBetween(String value1, String value2) {
			addCriterion("codice_stato_evento between", value1, value2, "codiceStatoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceStatoEventoNotBetween(String value1, String value2) {
			addCriterion("codice_stato_evento not between", value1, value2, "codiceStatoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceCertificationAuthorityIsNull() {
			addCriterion("codice_certification_authority is null");
			return (Criteria) this;
		}

		public Criteria andCodiceCertificationAuthorityIsNotNull() {
			addCriterion("codice_certification_authority is not null");
			return (Criteria) this;
		}

		public Criteria andCodiceCertificationAuthorityEqualTo(String value) {
			addCriterion("codice_certification_authority =", value, "codiceCertificationAuthority");
			return (Criteria) this;
		}

		public Criteria andCodiceCertificationAuthorityNotEqualTo(String value) {
			addCriterion("codice_certification_authority <>", value, "codiceCertificationAuthority");
			return (Criteria) this;
		}

		public Criteria andCodiceCertificationAuthorityGreaterThan(String value) {
			addCriterion("codice_certification_authority >", value, "codiceCertificationAuthority");
			return (Criteria) this;
		}

		public Criteria andCodiceCertificationAuthorityGreaterThanOrEqualTo(String value) {
			addCriterion("codice_certification_authority >=", value, "codiceCertificationAuthority");
			return (Criteria) this;
		}

		public Criteria andCodiceCertificationAuthorityLessThan(String value) {
			addCriterion("codice_certification_authority <", value, "codiceCertificationAuthority");
			return (Criteria) this;
		}

		public Criteria andCodiceCertificationAuthorityLessThanOrEqualTo(String value) {
			addCriterion("codice_certification_authority <=", value, "codiceCertificationAuthority");
			return (Criteria) this;
		}

		public Criteria andCodiceCertificationAuthorityLike(String value) {
			addCriterion("codice_certification_authority like", value, "codiceCertificationAuthority");
			return (Criteria) this;
		}

		public Criteria andCodiceCertificationAuthorityNotLike(String value) {
			addCriterion("codice_certification_authority not like", value, "codiceCertificationAuthority");
			return (Criteria) this;
		}

		public Criteria andCodiceCertificationAuthorityIn(List<String> values) {
			addCriterion("codice_certification_authority in", values, "codiceCertificationAuthority");
			return (Criteria) this;
		}

		public Criteria andCodiceCertificationAuthorityNotIn(List<String> values) {
			addCriterion("codice_certification_authority not in", values, "codiceCertificationAuthority");
			return (Criteria) this;
		}

		public Criteria andCodiceCertificationAuthorityBetween(String value1, String value2) {
			addCriterion("codice_certification_authority between", value1, value2, "codiceCertificationAuthority");
			return (Criteria) this;
		}

		public Criteria andCodiceCertificationAuthorityNotBetween(String value1, String value2) {
			addCriterion("codice_certification_authority not between", value1, value2, "codiceCertificationAuthority");
			return (Criteria) this;
		}

		public Criteria andCodiceApplicazioneIsNull() {
			addCriterion("codice_applicazione is null");
			return (Criteria) this;
		}

		public Criteria andCodiceApplicazioneIsNotNull() {
			addCriterion("codice_applicazione is not null");
			return (Criteria) this;
		}

		public Criteria andCodiceApplicazioneEqualTo(String value) {
			addCriterion("codice_applicazione =", value, "codiceApplicazione");
			return (Criteria) this;
		}

		public Criteria andCodiceApplicazioneNotEqualTo(String value) {
			addCriterion("codice_applicazione <>", value, "codiceApplicazione");
			return (Criteria) this;
		}

		public Criteria andCodiceApplicazioneGreaterThan(String value) {
			addCriterion("codice_applicazione >", value, "codiceApplicazione");
			return (Criteria) this;
		}

		public Criteria andCodiceApplicazioneGreaterThanOrEqualTo(String value) {
			addCriterion("codice_applicazione >=", value, "codiceApplicazione");
			return (Criteria) this;
		}

		public Criteria andCodiceApplicazioneLessThan(String value) {
			addCriterion("codice_applicazione <", value, "codiceApplicazione");
			return (Criteria) this;
		}

		public Criteria andCodiceApplicazioneLessThanOrEqualTo(String value) {
			addCriterion("codice_applicazione <=", value, "codiceApplicazione");
			return (Criteria) this;
		}

		public Criteria andCodiceApplicazioneLike(String value) {
			addCriterion("codice_applicazione like", value, "codiceApplicazione");
			return (Criteria) this;
		}

		public Criteria andCodiceApplicazioneNotLike(String value) {
			addCriterion("codice_applicazione not like", value, "codiceApplicazione");
			return (Criteria) this;
		}

		public Criteria andCodiceApplicazioneIn(List<String> values) {
			addCriterion("codice_applicazione in", values, "codiceApplicazione");
			return (Criteria) this;
		}

		public Criteria andCodiceApplicazioneNotIn(List<String> values) {
			addCriterion("codice_applicazione not in", values, "codiceApplicazione");
			return (Criteria) this;
		}

		public Criteria andCodiceApplicazioneBetween(String value1, String value2) {
			addCriterion("codice_applicazione between", value1, value2, "codiceApplicazione");
			return (Criteria) this;
		}

		public Criteria andCodiceApplicazioneNotBetween(String value1, String value2) {
			addCriterion("codice_applicazione not between", value1, value2, "codiceApplicazione");
			return (Criteria) this;
		}

		public Criteria andCodiceRepositoryIsNull() {
			addCriterion("codice_repository is null");
			return (Criteria) this;
		}

		public Criteria andCodiceRepositoryIsNotNull() {
			addCriterion("codice_repository is not null");
			return (Criteria) this;
		}

		public Criteria andCodiceRepositoryEqualTo(String value) {
			addCriterion("codice_repository =", value, "codiceRepository");
			return (Criteria) this;
		}

		public Criteria andCodiceRepositoryNotEqualTo(String value) {
			addCriterion("codice_repository <>", value, "codiceRepository");
			return (Criteria) this;
		}

		public Criteria andCodiceRepositoryGreaterThan(String value) {
			addCriterion("codice_repository >", value, "codiceRepository");
			return (Criteria) this;
		}

		public Criteria andCodiceRepositoryGreaterThanOrEqualTo(String value) {
			addCriterion("codice_repository >=", value, "codiceRepository");
			return (Criteria) this;
		}

		public Criteria andCodiceRepositoryLessThan(String value) {
			addCriterion("codice_repository <", value, "codiceRepository");
			return (Criteria) this;
		}

		public Criteria andCodiceRepositoryLessThanOrEqualTo(String value) {
			addCriterion("codice_repository <=", value, "codiceRepository");
			return (Criteria) this;
		}

		public Criteria andCodiceRepositoryLike(String value) {
			addCriterion("codice_repository like", value, "codiceRepository");
			return (Criteria) this;
		}

		public Criteria andCodiceRepositoryNotLike(String value) {
			addCriterion("codice_repository not like", value, "codiceRepository");
			return (Criteria) this;
		}

		public Criteria andCodiceRepositoryIn(List<String> values) {
			addCriterion("codice_repository in", values, "codiceRepository");
			return (Criteria) this;
		}

		public Criteria andCodiceRepositoryNotIn(List<String> values) {
			addCriterion("codice_repository not in", values, "codiceRepository");
			return (Criteria) this;
		}

		public Criteria andCodiceRepositoryBetween(String value1, String value2) {
			addCriterion("codice_repository between", value1, value2, "codiceRepository");
			return (Criteria) this;
		}

		public Criteria andCodiceRepositoryNotBetween(String value1, String value2) {
			addCriterion("codice_repository not between", value1, value2, "codiceRepository");
			return (Criteria) this;
		}

		public Criteria andCodiceOperazioneIsNull() {
			addCriterion("codice_operazione is null");
			return (Criteria) this;
		}

		public Criteria andCodiceOperazioneIsNotNull() {
			addCriterion("codice_operazione is not null");
			return (Criteria) this;
		}

		public Criteria andCodiceOperazioneEqualTo(String value) {
			addCriterion("codice_operazione =", value, "codiceOperazione");
			return (Criteria) this;
		}

		public Criteria andCodiceOperazioneNotEqualTo(String value) {
			addCriterion("codice_operazione <>", value, "codiceOperazione");
			return (Criteria) this;
		}

		public Criteria andCodiceOperazioneGreaterThan(String value) {
			addCriterion("codice_operazione >", value, "codiceOperazione");
			return (Criteria) this;
		}

		public Criteria andCodiceOperazioneGreaterThanOrEqualTo(String value) {
			addCriterion("codice_operazione >=", value, "codiceOperazione");
			return (Criteria) this;
		}

		public Criteria andCodiceOperazioneLessThan(String value) {
			addCriterion("codice_operazione <", value, "codiceOperazione");
			return (Criteria) this;
		}

		public Criteria andCodiceOperazioneLessThanOrEqualTo(String value) {
			addCriterion("codice_operazione <=", value, "codiceOperazione");
			return (Criteria) this;
		}

		public Criteria andCodiceOperazioneLike(String value) {
			addCriterion("codice_operazione like", value, "codiceOperazione");
			return (Criteria) this;
		}

		public Criteria andCodiceOperazioneNotLike(String value) {
			addCriterion("codice_operazione not like", value, "codiceOperazione");
			return (Criteria) this;
		}

		public Criteria andCodiceOperazioneIn(List<String> values) {
			addCriterion("codice_operazione in", values, "codiceOperazione");
			return (Criteria) this;
		}

		public Criteria andCodiceOperazioneNotIn(List<String> values) {
			addCriterion("codice_operazione not in", values, "codiceOperazione");
			return (Criteria) this;
		}

		public Criteria andCodiceOperazioneBetween(String value1, String value2) {
			addCriterion("codice_operazione between", value1, value2, "codiceOperazione");
			return (Criteria) this;
		}

		public Criteria andCodiceOperazioneNotBetween(String value1, String value2) {
			addCriterion("codice_operazione not between", value1, value2, "codiceOperazione");
			return (Criteria) this;
		}

		public Criteria andCodiceGatefireDTipoEventoIsNull() {
			addCriterion("codice_gatefire_d_tipo_evento is null");
			return (Criteria) this;
		}

		public Criteria andCodiceGatefireDTipoEventoIsNotNull() {
			addCriterion("codice_gatefire_d_tipo_evento is not null");
			return (Criteria) this;
		}

		public Criteria andCodiceGatefireDTipoEventoEqualTo(String value) {
			addCriterion("codice_gatefire_d_tipo_evento =", value, "codiceGatefireDTipoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceGatefireDTipoEventoNotEqualTo(String value) {
			addCriterion("codice_gatefire_d_tipo_evento <>", value, "codiceGatefireDTipoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceGatefireDTipoEventoGreaterThan(String value) {
			addCriterion("codice_gatefire_d_tipo_evento >", value, "codiceGatefireDTipoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceGatefireDTipoEventoGreaterThanOrEqualTo(String value) {
			addCriterion("codice_gatefire_d_tipo_evento >=", value, "codiceGatefireDTipoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceGatefireDTipoEventoLessThan(String value) {
			addCriterion("codice_gatefire_d_tipo_evento <", value, "codiceGatefireDTipoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceGatefireDTipoEventoLessThanOrEqualTo(String value) {
			addCriterion("codice_gatefire_d_tipo_evento <=", value, "codiceGatefireDTipoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceGatefireDTipoEventoLike(String value) {
			addCriterion("codice_gatefire_d_tipo_evento like", value, "codiceGatefireDTipoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceGatefireDTipoEventoNotLike(String value) {
			addCriterion("codice_gatefire_d_tipo_evento not like", value, "codiceGatefireDTipoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceGatefireDTipoEventoIn(List<String> values) {
			addCriterion("codice_gatefire_d_tipo_evento in", values, "codiceGatefireDTipoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceGatefireDTipoEventoNotIn(List<String> values) {
			addCriterion("codice_gatefire_d_tipo_evento not in", values, "codiceGatefireDTipoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceGatefireDTipoEventoBetween(String value1, String value2) {
			addCriterion("codice_gatefire_d_tipo_evento between", value1, value2, "codiceGatefireDTipoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceGatefireDTipoEventoNotBetween(String value1, String value2) {
			addCriterion("codice_gatefire_d_tipo_evento not between", value1, value2, "codiceGatefireDTipoEvento");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneIsNull() {
			addCriterion("data_cancellazione is null");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneIsNotNull() {
			addCriterion("data_cancellazione is not null");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneEqualTo(Date value) {
			addCriterion("data_cancellazione =", value, "dataCancellazione");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneNotEqualTo(Date value) {
			addCriterion("data_cancellazione <>", value, "dataCancellazione");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneGreaterThan(Date value) {
			addCriterion("data_cancellazione >", value, "dataCancellazione");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneGreaterThanOrEqualTo(Date value) {
			addCriterion("data_cancellazione >=", value, "dataCancellazione");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneLessThan(Date value) {
			addCriterion("data_cancellazione <", value, "dataCancellazione");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneLessThanOrEqualTo(Date value) {
			addCriterion("data_cancellazione <=", value, "dataCancellazione");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneIn(List<Date> values) {
			addCriterion("data_cancellazione in", values, "dataCancellazione");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneNotIn(List<Date> values) {
			addCriterion("data_cancellazione not in", values, "dataCancellazione");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneBetween(Date value1, Date value2) {
			addCriterion("data_cancellazione between", value1, value2, "dataCancellazione");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneNotBetween(Date value1, Date value2) {
			addCriterion("data_cancellazione not between", value1, value2, "dataCancellazione");
			return (Criteria) this;
		}

		public Criteria andCollocazioneIsNull() {
			addCriterion("collocazione is null");
			return (Criteria) this;
		}

		public Criteria andCollocazioneIsNotNull() {
			addCriterion("collocazione is not null");
			return (Criteria) this;
		}

		public Criteria andCollocazioneEqualTo(String value) {
			addCriterion("collocazione =", value, "collocazione");
			return (Criteria) this;
		}

		public Criteria andCollocazioneNotEqualTo(String value) {
			addCriterion("collocazione <>", value, "collocazione");
			return (Criteria) this;
		}

		public Criteria andCollocazioneGreaterThan(String value) {
			addCriterion("collocazione >", value, "collocazione");
			return (Criteria) this;
		}

		public Criteria andCollocazioneGreaterThanOrEqualTo(String value) {
			addCriterion("collocazione >=", value, "collocazione");
			return (Criteria) this;
		}

		public Criteria andCollocazioneLessThan(String value) {
			addCriterion("collocazione <", value, "collocazione");
			return (Criteria) this;
		}

		public Criteria andCollocazioneLessThanOrEqualTo(String value) {
			addCriterion("collocazione <=", value, "collocazione");
			return (Criteria) this;
		}

		public Criteria andCollocazioneLike(String value) {
			addCriterion("collocazione like", value, "collocazione");
			return (Criteria) this;
		}

		public Criteria andCollocazioneNotLike(String value) {
			addCriterion("collocazione not like", value, "collocazione");
			return (Criteria) this;
		}

		public Criteria andCollocazioneIn(List<String> values) {
			addCriterion("collocazione in", values, "collocazione");
			return (Criteria) this;
		}

		public Criteria andCollocazioneNotIn(List<String> values) {
			addCriterion("collocazione not in", values, "collocazione");
			return (Criteria) this;
		}

		public Criteria andCollocazioneBetween(String value1, String value2) {
			addCriterion("collocazione between", value1, value2, "collocazione");
			return (Criteria) this;
		}

		public Criteria andCollocazioneNotBetween(String value1, String value2) {
			addCriterion("collocazione not between", value1, value2, "collocazione");
			return (Criteria) this;
		}

		public Criteria andIdUtenteLikeInsensitive(String value) {
			addCriterion("upper(id_utente) like", value.toUpperCase(), "idUtente");
			return (Criteria) this;
		}

		public Criteria andIdSessioneLikeInsensitive(String value) {
			addCriterion("upper(id_sessione) like", value.toUpperCase(), "idSessione");
			return (Criteria) this;
		}

		public Criteria andCodiceFiscaleLikeInsensitive(String value) {
			addCriterion("upper(codice_fiscale) like", value.toUpperCase(), "codiceFiscale");
			return (Criteria) this;
		}

		public Criteria andIpApplicazioneLikeInsensitive(String value) {
			addCriterion("upper(ip_applicazione) like", value.toUpperCase(), "ipApplicazione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneLikeInsensitive(String value) {
			addCriterion("upper(descrizione) like", value.toUpperCase(), "descrizione");
			return (Criteria) this;
		}

		public Criteria andNomeFileLikeInsensitive(String value) {
			addCriterion("upper(nome_file) like", value.toUpperCase(), "nomeFile");
			return (Criteria) this;
		}

		public Criteria andCodiceStatoEventoLikeInsensitive(String value) {
			addCriterion("upper(codice_stato_evento) like", value.toUpperCase(), "codiceStatoEvento");
			return (Criteria) this;
		}

		public Criteria andCodiceCertificationAuthorityLikeInsensitive(String value) {
			addCriterion("upper(codice_certification_authority) like", value.toUpperCase(),
					"codiceCertificationAuthority");
			return (Criteria) this;
		}

		public Criteria andCodiceApplicazioneLikeInsensitive(String value) {
			addCriterion("upper(codice_applicazione) like", value.toUpperCase(), "codiceApplicazione");
			return (Criteria) this;
		}

		public Criteria andCodiceRepositoryLikeInsensitive(String value) {
			addCriterion("upper(codice_repository) like", value.toUpperCase(), "codiceRepository");
			return (Criteria) this;
		}

		public Criteria andCodiceOperazioneLikeInsensitive(String value) {
			addCriterion("upper(codice_operazione) like", value.toUpperCase(), "codiceOperazione");
			return (Criteria) this;
		}

		public Criteria andCodiceGatefireDTipoEventoLikeInsensitive(String value) {
			addCriterion("upper(codice_gatefire_d_tipo_evento) like", value.toUpperCase(), "codiceGatefireDTipoEvento");
			return (Criteria) this;
		}

		public Criteria andCollocazioneLikeInsensitive(String value) {
			addCriterion("upper(collocazione) like", value.toUpperCase(), "collocazione");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table gatefire.gatefire_l_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gatefire.gatefire_l_evento
     *
     * @mbg.generated do_not_delete_during_merge Tue Sep 29 14:10:47 CEST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}