package it.csi.gatefire.dbhelper.model;

import java.util.Date;
import java.util.List;

public class GatefireLEvento {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento.id
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento.data_inizio_elab
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	private Date dataInizioElab;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento.data_fine_elab
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	private Date dataFineElab;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento.data_agg_stato
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	private Date dataAggStato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento.data_creazione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento.id_utente
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	private String idUtente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento.id_sessione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	private String idSessione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento.codice_fiscale
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	private String codiceFiscale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento.ip_applicazione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	private String ipApplicazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento.descrizione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	private String descrizione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento.nome_file
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	private String nomeFile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento.codice_stato_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	private String codiceStatoEvento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento.codice_certification_authority
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	private String codiceCertificationAuthority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento.codice_applicazione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	private String codiceApplicazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento.codice_repository
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	private String codiceRepository;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento.codice_operazione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	private String codiceOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento.codice_gatefire_d_tipo_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	private String codiceGatefireDTipoEvento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento.data_cancellazione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento.collocazione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	private String collocazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento.id
	 * @return  the value of gatefire.gatefire_l_evento.id
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento.id
	 * @param id  the value for gatefire.gatefire_l_evento.id
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento.data_inizio_elab
	 * @return  the value of gatefire.gatefire_l_evento.data_inizio_elab
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public Date getDataInizioElab() {
		return dataInizioElab;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento.data_inizio_elab
	 * @param dataInizioElab  the value for gatefire.gatefire_l_evento.data_inizio_elab
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void setDataInizioElab(Date dataInizioElab) {
		this.dataInizioElab = dataInizioElab;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento.data_fine_elab
	 * @return  the value of gatefire.gatefire_l_evento.data_fine_elab
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public Date getDataFineElab() {
		return dataFineElab;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento.data_fine_elab
	 * @param dataFineElab  the value for gatefire.gatefire_l_evento.data_fine_elab
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void setDataFineElab(Date dataFineElab) {
		this.dataFineElab = dataFineElab;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento.data_agg_stato
	 * @return  the value of gatefire.gatefire_l_evento.data_agg_stato
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public Date getDataAggStato() {
		return dataAggStato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento.data_agg_stato
	 * @param dataAggStato  the value for gatefire.gatefire_l_evento.data_agg_stato
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void setDataAggStato(Date dataAggStato) {
		this.dataAggStato = dataAggStato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento.data_creazione
	 * @return  the value of gatefire.gatefire_l_evento.data_creazione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento.data_creazione
	 * @param dataCreazione  the value for gatefire.gatefire_l_evento.data_creazione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento.id_utente
	 * @return  the value of gatefire.gatefire_l_evento.id_utente
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public String getIdUtente() {
		return idUtente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento.id_utente
	 * @param idUtente  the value for gatefire.gatefire_l_evento.id_utente
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void setIdUtente(String idUtente) {
		this.idUtente = idUtente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento.id_sessione
	 * @return  the value of gatefire.gatefire_l_evento.id_sessione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public String getIdSessione() {
		return idSessione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento.id_sessione
	 * @param idSessione  the value for gatefire.gatefire_l_evento.id_sessione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void setIdSessione(String idSessione) {
		this.idSessione = idSessione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento.codice_fiscale
	 * @return  the value of gatefire.gatefire_l_evento.codice_fiscale
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public String getCodiceFiscale() {
		return codiceFiscale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento.codice_fiscale
	 * @param codiceFiscale  the value for gatefire.gatefire_l_evento.codice_fiscale
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void setCodiceFiscale(String codiceFiscale) {
		this.codiceFiscale = codiceFiscale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento.ip_applicazione
	 * @return  the value of gatefire.gatefire_l_evento.ip_applicazione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public String getIpApplicazione() {
		return ipApplicazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento.ip_applicazione
	 * @param ipApplicazione  the value for gatefire.gatefire_l_evento.ip_applicazione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void setIpApplicazione(String ipApplicazione) {
		this.ipApplicazione = ipApplicazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento.descrizione
	 * @return  the value of gatefire.gatefire_l_evento.descrizione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public String getDescrizione() {
		return descrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento.descrizione
	 * @param descrizione  the value for gatefire.gatefire_l_evento.descrizione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento.nome_file
	 * @return  the value of gatefire.gatefire_l_evento.nome_file
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public String getNomeFile() {
		return nomeFile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento.nome_file
	 * @param nomeFile  the value for gatefire.gatefire_l_evento.nome_file
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void setNomeFile(String nomeFile) {
		this.nomeFile = nomeFile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento.codice_stato_evento
	 * @return  the value of gatefire.gatefire_l_evento.codice_stato_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public String getCodiceStatoEvento() {
		return codiceStatoEvento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento.codice_stato_evento
	 * @param codiceStatoEvento  the value for gatefire.gatefire_l_evento.codice_stato_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void setCodiceStatoEvento(String codiceStatoEvento) {
		this.codiceStatoEvento = codiceStatoEvento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento.codice_certification_authority
	 * @return  the value of gatefire.gatefire_l_evento.codice_certification_authority
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public String getCodiceCertificationAuthority() {
		return codiceCertificationAuthority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento.codice_certification_authority
	 * @param codiceCertificationAuthority  the value for gatefire.gatefire_l_evento.codice_certification_authority
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void setCodiceCertificationAuthority(String codiceCertificationAuthority) {
		this.codiceCertificationAuthority = codiceCertificationAuthority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento.codice_applicazione
	 * @return  the value of gatefire.gatefire_l_evento.codice_applicazione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public String getCodiceApplicazione() {
		return codiceApplicazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento.codice_applicazione
	 * @param codiceApplicazione  the value for gatefire.gatefire_l_evento.codice_applicazione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void setCodiceApplicazione(String codiceApplicazione) {
		this.codiceApplicazione = codiceApplicazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento.codice_repository
	 * @return  the value of gatefire.gatefire_l_evento.codice_repository
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public String getCodiceRepository() {
		return codiceRepository;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento.codice_repository
	 * @param codiceRepository  the value for gatefire.gatefire_l_evento.codice_repository
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void setCodiceRepository(String codiceRepository) {
		this.codiceRepository = codiceRepository;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento.codice_operazione
	 * @return  the value of gatefire.gatefire_l_evento.codice_operazione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public String getCodiceOperazione() {
		return codiceOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento.codice_operazione
	 * @param codiceOperazione  the value for gatefire.gatefire_l_evento.codice_operazione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void setCodiceOperazione(String codiceOperazione) {
		this.codiceOperazione = codiceOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento.codice_gatefire_d_tipo_evento
	 * @return  the value of gatefire.gatefire_l_evento.codice_gatefire_d_tipo_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public String getCodiceGatefireDTipoEvento() {
		return codiceGatefireDTipoEvento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento.codice_gatefire_d_tipo_evento
	 * @param codiceGatefireDTipoEvento  the value for gatefire.gatefire_l_evento.codice_gatefire_d_tipo_evento
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void setCodiceGatefireDTipoEvento(String codiceGatefireDTipoEvento) {
		this.codiceGatefireDTipoEvento = codiceGatefireDTipoEvento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento.data_cancellazione
	 * @return  the value of gatefire.gatefire_l_evento.data_cancellazione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento.data_cancellazione
	 * @param dataCancellazione  the value for gatefire.gatefire_l_evento.data_cancellazione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento.collocazione
	 * @return  the value of gatefire.gatefire_l_evento.collocazione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public String getCollocazione() {
		return collocazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento.collocazione
	 * @param collocazione  the value for gatefire.gatefire_l_evento.collocazione
	 * @mbg.generated  Tue Apr 06 09:42:38 CEST 2021
	 */
	public void setCollocazione(String collocazione) {
		this.collocazione = collocazione;
	}

	private List<GatefireLEventoStep> eventoStepList;

	public List<GatefireLEventoStep> getEventoStepList() {
		return eventoStepList;
	}

	public void setEventoStepList(List<GatefireLEventoStep> eventoStepList) {
		this.eventoStepList = eventoStepList;
	}

	public GatefireLEvento() {
		super();

	}

	public GatefireLEvento(Date data) {
		super();
		this.dataInizioElab = data;

		this.dataAggStato = data;
		this.dataCreazione = data;
	}

	private Long idEventoPadre;
	private Long idEventoFiglio;

	public Long getIdEventoPadre() {
		return idEventoPadre;
	}

	public void setIdEventoPadre(Long idEventoPadre) {
		this.idEventoPadre = idEventoPadre;
	}

	public Long getIdEventoFiglio() {
		return idEventoFiglio;
	}

	public void setIdEventoFiglio(Long idEventoFiglio) {
		this.idEventoFiglio = idEventoFiglio;
	}

}