/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gatefire.dbhelper.model;

import java.util.Date;

public class GatefireDCaCollocazioneDominio extends GatefireDCaCollocazioneDominioKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_ca_collocazione_dominio.configurazione
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	private String configurazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_ca_collocazione_dominio.data_inizio_validita
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	private Date dataInizioValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_ca_collocazione_dominio.data_fine_validita
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	private Date dataFineValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_ca_collocazione_dominio.data_creazione
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_ca_collocazione_dominio.data_aggiornamento
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	private Date dataAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_ca_collocazione_dominio.data_cancellazione
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_ca_collocazione_dominio.configurazione
	 * @return  the value of gatefire.gatefire_d_ca_collocazione_dominio.configurazione
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	public String getConfigurazione() {
		return configurazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_ca_collocazione_dominio.configurazione
	 * @param configurazione  the value for gatefire.gatefire_d_ca_collocazione_dominio.configurazione
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	public void setConfigurazione(String configurazione) {
		this.configurazione = configurazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_ca_collocazione_dominio.data_inizio_validita
	 * @return  the value of gatefire.gatefire_d_ca_collocazione_dominio.data_inizio_validita
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	public Date getDataInizioValidita() {
		return dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_ca_collocazione_dominio.data_inizio_validita
	 * @param dataInizioValidita  the value for gatefire.gatefire_d_ca_collocazione_dominio.data_inizio_validita
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	public void setDataInizioValidita(Date dataInizioValidita) {
		this.dataInizioValidita = dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_ca_collocazione_dominio.data_fine_validita
	 * @return  the value of gatefire.gatefire_d_ca_collocazione_dominio.data_fine_validita
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	public Date getDataFineValidita() {
		return dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_ca_collocazione_dominio.data_fine_validita
	 * @param dataFineValidita  the value for gatefire.gatefire_d_ca_collocazione_dominio.data_fine_validita
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	public void setDataFineValidita(Date dataFineValidita) {
		this.dataFineValidita = dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_ca_collocazione_dominio.data_creazione
	 * @return  the value of gatefire.gatefire_d_ca_collocazione_dominio.data_creazione
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_ca_collocazione_dominio.data_creazione
	 * @param dataCreazione  the value for gatefire.gatefire_d_ca_collocazione_dominio.data_creazione
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_ca_collocazione_dominio.data_aggiornamento
	 * @return  the value of gatefire.gatefire_d_ca_collocazione_dominio.data_aggiornamento
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_ca_collocazione_dominio.data_aggiornamento
	 * @param dataAggiornamento  the value for gatefire.gatefire_d_ca_collocazione_dominio.data_aggiornamento
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_ca_collocazione_dominio.data_cancellazione
	 * @return  the value of gatefire.gatefire_d_ca_collocazione_dominio.data_cancellazione
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_ca_collocazione_dominio.data_cancellazione
	 * @param dataCancellazione  the value for gatefire.gatefire_d_ca_collocazione_dominio.data_cancellazione
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}