package it.csi.gatefire.dbhelper.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GatefireDVersioneExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public GatefireDVersioneExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Short value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Short value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Short value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Short value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Short value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Short value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Short> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Short> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Short value1, Short value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Short value1, Short value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDataIsNull() {
            addCriterion("data is null");
            return (Criteria) this;
        }

        public Criteria andDataIsNotNull() {
            addCriterion("data is not null");
            return (Criteria) this;
        }

        public Criteria andDataEqualTo(Date value) {
            addCriterion("data =", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataNotEqualTo(Date value) {
            addCriterion("data <>", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataGreaterThan(Date value) {
            addCriterion("data >", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataGreaterThanOrEqualTo(Date value) {
            addCriterion("data >=", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataLessThan(Date value) {
            addCriterion("data <", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataLessThanOrEqualTo(Date value) {
            addCriterion("data <=", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataIn(List<Date> values) {
            addCriterion("data in", values, "data");
            return (Criteria) this;
        }

        public Criteria andDataNotIn(List<Date> values) {
            addCriterion("data not in", values, "data");
            return (Criteria) this;
        }

        public Criteria andDataBetween(Date value1, Date value2) {
            addCriterion("data between", value1, value2, "data");
            return (Criteria) this;
        }

        public Criteria andDataNotBetween(Date value1, Date value2) {
            addCriterion("data not between", value1, value2, "data");
            return (Criteria) this;
        }

        public Criteria andNumeroIsNull() {
            addCriterion("numero is null");
            return (Criteria) this;
        }

        public Criteria andNumeroIsNotNull() {
            addCriterion("numero is not null");
            return (Criteria) this;
        }

        public Criteria andNumeroEqualTo(String value) {
            addCriterion("numero =", value, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroNotEqualTo(String value) {
            addCriterion("numero <>", value, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroGreaterThan(String value) {
            addCriterion("numero >", value, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroGreaterThanOrEqualTo(String value) {
            addCriterion("numero >=", value, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroLessThan(String value) {
            addCriterion("numero <", value, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroLessThanOrEqualTo(String value) {
            addCriterion("numero <=", value, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroLike(String value) {
            addCriterion("numero like", value, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroNotLike(String value) {
            addCriterion("numero not like", value, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroIn(List<String> values) {
            addCriterion("numero in", values, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroNotIn(List<String> values) {
            addCriterion("numero not in", values, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroBetween(String value1, String value2) {
            addCriterion("numero between", value1, value2, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroNotBetween(String value1, String value2) {
            addCriterion("numero not between", value1, value2, "numero");
            return (Criteria) this;
        }

        public Criteria andContenutoIsNull() {
            addCriterion("contenuto is null");
            return (Criteria) this;
        }

        public Criteria andContenutoIsNotNull() {
            addCriterion("contenuto is not null");
            return (Criteria) this;
        }

        public Criteria andContenutoEqualTo(String value) {
            addCriterion("contenuto =", value, "contenuto");
            return (Criteria) this;
        }

        public Criteria andContenutoNotEqualTo(String value) {
            addCriterion("contenuto <>", value, "contenuto");
            return (Criteria) this;
        }

        public Criteria andContenutoGreaterThan(String value) {
            addCriterion("contenuto >", value, "contenuto");
            return (Criteria) this;
        }

        public Criteria andContenutoGreaterThanOrEqualTo(String value) {
            addCriterion("contenuto >=", value, "contenuto");
            return (Criteria) this;
        }

        public Criteria andContenutoLessThan(String value) {
            addCriterion("contenuto <", value, "contenuto");
            return (Criteria) this;
        }

        public Criteria andContenutoLessThanOrEqualTo(String value) {
            addCriterion("contenuto <=", value, "contenuto");
            return (Criteria) this;
        }

        public Criteria andContenutoLike(String value) {
            addCriterion("contenuto like", value, "contenuto");
            return (Criteria) this;
        }

        public Criteria andContenutoNotLike(String value) {
            addCriterion("contenuto not like", value, "contenuto");
            return (Criteria) this;
        }

        public Criteria andContenutoIn(List<String> values) {
            addCriterion("contenuto in", values, "contenuto");
            return (Criteria) this;
        }

        public Criteria andContenutoNotIn(List<String> values) {
            addCriterion("contenuto not in", values, "contenuto");
            return (Criteria) this;
        }

        public Criteria andContenutoBetween(String value1, String value2) {
            addCriterion("contenuto between", value1, value2, "contenuto");
            return (Criteria) this;
        }

        public Criteria andContenutoNotBetween(String value1, String value2) {
            addCriterion("contenuto not between", value1, value2, "contenuto");
            return (Criteria) this;
        }

        public Criteria andDataCreazioneIsNull() {
            addCriterion("data_creazione is null");
            return (Criteria) this;
        }

        public Criteria andDataCreazioneIsNotNull() {
            addCriterion("data_creazione is not null");
            return (Criteria) this;
        }

        public Criteria andDataCreazioneEqualTo(Date value) {
            addCriterion("data_creazione =", value, "dataCreazione");
            return (Criteria) this;
        }

        public Criteria andDataCreazioneNotEqualTo(Date value) {
            addCriterion("data_creazione <>", value, "dataCreazione");
            return (Criteria) this;
        }

        public Criteria andDataCreazioneGreaterThan(Date value) {
            addCriterion("data_creazione >", value, "dataCreazione");
            return (Criteria) this;
        }

        public Criteria andDataCreazioneGreaterThanOrEqualTo(Date value) {
            addCriterion("data_creazione >=", value, "dataCreazione");
            return (Criteria) this;
        }

        public Criteria andDataCreazioneLessThan(Date value) {
            addCriterion("data_creazione <", value, "dataCreazione");
            return (Criteria) this;
        }

        public Criteria andDataCreazioneLessThanOrEqualTo(Date value) {
            addCriterion("data_creazione <=", value, "dataCreazione");
            return (Criteria) this;
        }

        public Criteria andDataCreazioneIn(List<Date> values) {
            addCriterion("data_creazione in", values, "dataCreazione");
            return (Criteria) this;
        }

        public Criteria andDataCreazioneNotIn(List<Date> values) {
            addCriterion("data_creazione not in", values, "dataCreazione");
            return (Criteria) this;
        }

        public Criteria andDataCreazioneBetween(Date value1, Date value2) {
            addCriterion("data_creazione between", value1, value2, "dataCreazione");
            return (Criteria) this;
        }

        public Criteria andDataCreazioneNotBetween(Date value1, Date value2) {
            addCriterion("data_creazione not between", value1, value2, "dataCreazione");
            return (Criteria) this;
        }

        public Criteria andNumeroLikeInsensitive(String value) {
            addCriterion("upper(numero) like", value.toUpperCase(), "numero");
            return (Criteria) this;
        }

        public Criteria andContenutoLikeInsensitive(String value) {
            addCriterion("upper(contenuto) like", value.toUpperCase(), "contenuto");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated do_not_delete_during_merge Wed Nov 25 11:01:29 CET 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gatefire.gatefire_d_versione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}