/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gatefire.dbhelper.model;

import java.util.Date;

public class GatefireDUso {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_uso.uso
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private String uso;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_uso.descrizione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private String descrizione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_uso.data_creazione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_uso.data_aggiornamento
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private Date dataAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_uso.data_cancellazione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_uso.uso
	 * @return  the value of gatefire.gatefire_d_uso.uso
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public String getUso() {
		return uso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_uso.uso
	 * @param uso  the value for gatefire.gatefire_d_uso.uso
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setUso(String uso) {
		this.uso = uso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_uso.descrizione
	 * @return  the value of gatefire.gatefire_d_uso.descrizione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public String getDescrizione() {
		return descrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_uso.descrizione
	 * @param descrizione  the value for gatefire.gatefire_d_uso.descrizione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_uso.data_creazione
	 * @return  the value of gatefire.gatefire_d_uso.data_creazione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_uso.data_creazione
	 * @param dataCreazione  the value for gatefire.gatefire_d_uso.data_creazione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_uso.data_aggiornamento
	 * @return  the value of gatefire.gatefire_d_uso.data_aggiornamento
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_uso.data_aggiornamento
	 * @param dataAggiornamento  the value for gatefire.gatefire_d_uso.data_aggiornamento
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_uso.data_cancellazione
	 * @return  the value of gatefire.gatefire_d_uso.data_cancellazione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_uso.data_cancellazione
	 * @param dataCancellazione  the value for gatefire.gatefire_d_uso.data_cancellazione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}