package it.csi.gatefire.dbhelper.model;

import java.util.Date;

public class GatefireDVersione {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gatefire.gatefire_d_versione.id
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gatefire.gatefire_d_versione.data
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    private Date data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gatefire.gatefire_d_versione.numero
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    private String numero;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gatefire.gatefire_d_versione.contenuto
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    private String contenuto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gatefire.gatefire_d_versione.data_creazione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    private Date dataCreazione;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gatefire.gatefire_d_versione.id
     *
     * @return the value of gatefire.gatefire_d_versione.id
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gatefire.gatefire_d_versione.id
     *
     * @param id the value for gatefire.gatefire_d_versione.id
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gatefire.gatefire_d_versione.data
     *
     * @return the value of gatefire.gatefire_d_versione.data
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public Date getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gatefire.gatefire_d_versione.data
     *
     * @param data the value for gatefire.gatefire_d_versione.data
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public void setData(Date data) {
        this.data = data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gatefire.gatefire_d_versione.numero
     *
     * @return the value of gatefire.gatefire_d_versione.numero
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public String getNumero() {
        return numero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gatefire.gatefire_d_versione.numero
     *
     * @param numero the value for gatefire.gatefire_d_versione.numero
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public void setNumero(String numero) {
        this.numero = numero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gatefire.gatefire_d_versione.contenuto
     *
     * @return the value of gatefire.gatefire_d_versione.contenuto
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public String getContenuto() {
        return contenuto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gatefire.gatefire_d_versione.contenuto
     *
     * @param contenuto the value for gatefire.gatefire_d_versione.contenuto
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public void setContenuto(String contenuto) {
        this.contenuto = contenuto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gatefire.gatefire_d_versione.data_creazione
     *
     * @return the value of gatefire.gatefire_d_versione.data_creazione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public Date getDataCreazione() {
        return dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gatefire.gatefire_d_versione.data_creazione
     *
     * @param dataCreazione the value for gatefire.gatefire_d_versione.data_creazione
     *
     * @mbg.generated Wed Nov 25 11:01:29 CET 2020
     */
    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }
}