/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gatefire.dbhelper.model;

import java.util.Date;

public class GatefireDLivelloMessaggio {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_livello_messaggio.tipo
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private String tipo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_livello_messaggio.descrizione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private String descrizione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_livello_messaggio.data_creazione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_livello_messaggio.data_aggiornamento
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private Date dataAggiornamento;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_livello_messaggio.tipo
	 * @return  the value of gatefire.gatefire_d_livello_messaggio.tipo
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public String getTipo() {
		return tipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_livello_messaggio.tipo
	 * @param tipo  the value for gatefire.gatefire_d_livello_messaggio.tipo
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_livello_messaggio.descrizione
	 * @return  the value of gatefire.gatefire_d_livello_messaggio.descrizione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public String getDescrizione() {
		return descrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_livello_messaggio.descrizione
	 * @param descrizione  the value for gatefire.gatefire_d_livello_messaggio.descrizione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_livello_messaggio.data_creazione
	 * @return  the value of gatefire.gatefire_d_livello_messaggio.data_creazione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_livello_messaggio.data_creazione
	 * @param dataCreazione  the value for gatefire.gatefire_d_livello_messaggio.data_creazione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_livello_messaggio.data_aggiornamento
	 * @return  the value of gatefire.gatefire_d_livello_messaggio.data_aggiornamento
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_livello_messaggio.data_aggiornamento
	 * @param dataAggiornamento  the value for gatefire.gatefire_d_livello_messaggio.data_aggiornamento
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}
}