package it.csi.gatefire.dbhelper.model;

import java.util.Date;

public class GatefireDTagCa {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_tag_ca.nome
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private String nome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_tag_ca.descrizione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private String descrizione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_tag_ca.data_inizio_validita
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private Date dataInizioValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_tag_ca.data_fine_validita
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private Date dataFineValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_tag_ca.data_creazione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_tag_ca.data_aggiornamento
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private Date dataAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_tag_ca.data_cancellazione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_tag_ca.nome
	 * @return  the value of gatefire.gatefire_d_tag_ca.nome
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public String getNome() {
		return nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_tag_ca.nome
	 * @param nome  the value for gatefire.gatefire_d_tag_ca.nome
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_tag_ca.descrizione
	 * @return  the value of gatefire.gatefire_d_tag_ca.descrizione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public String getDescrizione() {
		return descrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_tag_ca.descrizione
	 * @param descrizione  the value for gatefire.gatefire_d_tag_ca.descrizione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_tag_ca.data_inizio_validita
	 * @return  the value of gatefire.gatefire_d_tag_ca.data_inizio_validita
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public Date getDataInizioValidita() {
		return dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_tag_ca.data_inizio_validita
	 * @param dataInizioValidita  the value for gatefire.gatefire_d_tag_ca.data_inizio_validita
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setDataInizioValidita(Date dataInizioValidita) {
		this.dataInizioValidita = dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_tag_ca.data_fine_validita
	 * @return  the value of gatefire.gatefire_d_tag_ca.data_fine_validita
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public Date getDataFineValidita() {
		return dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_tag_ca.data_fine_validita
	 * @param dataFineValidita  the value for gatefire.gatefire_d_tag_ca.data_fine_validita
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setDataFineValidita(Date dataFineValidita) {
		this.dataFineValidita = dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_tag_ca.data_creazione
	 * @return  the value of gatefire.gatefire_d_tag_ca.data_creazione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_tag_ca.data_creazione
	 * @param dataCreazione  the value for gatefire.gatefire_d_tag_ca.data_creazione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_tag_ca.data_aggiornamento
	 * @return  the value of gatefire.gatefire_d_tag_ca.data_aggiornamento
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_tag_ca.data_aggiornamento
	 * @param dataAggiornamento  the value for gatefire.gatefire_d_tag_ca.data_aggiornamento
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_tag_ca.data_cancellazione
	 * @return  the value of gatefire.gatefire_d_tag_ca.data_cancellazione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_tag_ca.data_cancellazione
	 * @param dataCancellazione  the value for gatefire.gatefire_d_tag_ca.data_cancellazione
	 * @mbg.generated  Fri Jan 29 11:47:25 CET 2021
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}