/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gatefire.dbhelper.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GatefireDApplicazioneExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	public GatefireDApplicazioneExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodiceIsNull() {
			addCriterion("codice is null");
			return (Criteria) this;
		}

		public Criteria andCodiceIsNotNull() {
			addCriterion("codice is not null");
			return (Criteria) this;
		}

		public Criteria andCodiceEqualTo(String value) {
			addCriterion("codice =", value, "codice");
			return (Criteria) this;
		}

		public Criteria andCodiceNotEqualTo(String value) {
			addCriterion("codice <>", value, "codice");
			return (Criteria) this;
		}

		public Criteria andCodiceGreaterThan(String value) {
			addCriterion("codice >", value, "codice");
			return (Criteria) this;
		}

		public Criteria andCodiceGreaterThanOrEqualTo(String value) {
			addCriterion("codice >=", value, "codice");
			return (Criteria) this;
		}

		public Criteria andCodiceLessThan(String value) {
			addCriterion("codice <", value, "codice");
			return (Criteria) this;
		}

		public Criteria andCodiceLessThanOrEqualTo(String value) {
			addCriterion("codice <=", value, "codice");
			return (Criteria) this;
		}

		public Criteria andCodiceLike(String value) {
			addCriterion("codice like", value, "codice");
			return (Criteria) this;
		}

		public Criteria andCodiceNotLike(String value) {
			addCriterion("codice not like", value, "codice");
			return (Criteria) this;
		}

		public Criteria andCodiceIn(List<String> values) {
			addCriterion("codice in", values, "codice");
			return (Criteria) this;
		}

		public Criteria andCodiceNotIn(List<String> values) {
			addCriterion("codice not in", values, "codice");
			return (Criteria) this;
		}

		public Criteria andCodiceBetween(String value1, String value2) {
			addCriterion("codice between", value1, value2, "codice");
			return (Criteria) this;
		}

		public Criteria andCodiceNotBetween(String value1, String value2) {
			addCriterion("codice not between", value1, value2, "codice");
			return (Criteria) this;
		}

		public Criteria andNomeIsNull() {
			addCriterion("nome is null");
			return (Criteria) this;
		}

		public Criteria andNomeIsNotNull() {
			addCriterion("nome is not null");
			return (Criteria) this;
		}

		public Criteria andNomeEqualTo(String value) {
			addCriterion("nome =", value, "nome");
			return (Criteria) this;
		}

		public Criteria andNomeNotEqualTo(String value) {
			addCriterion("nome <>", value, "nome");
			return (Criteria) this;
		}

		public Criteria andNomeGreaterThan(String value) {
			addCriterion("nome >", value, "nome");
			return (Criteria) this;
		}

		public Criteria andNomeGreaterThanOrEqualTo(String value) {
			addCriterion("nome >=", value, "nome");
			return (Criteria) this;
		}

		public Criteria andNomeLessThan(String value) {
			addCriterion("nome <", value, "nome");
			return (Criteria) this;
		}

		public Criteria andNomeLessThanOrEqualTo(String value) {
			addCriterion("nome <=", value, "nome");
			return (Criteria) this;
		}

		public Criteria andNomeLike(String value) {
			addCriterion("nome like", value, "nome");
			return (Criteria) this;
		}

		public Criteria andNomeNotLike(String value) {
			addCriterion("nome not like", value, "nome");
			return (Criteria) this;
		}

		public Criteria andNomeIn(List<String> values) {
			addCriterion("nome in", values, "nome");
			return (Criteria) this;
		}

		public Criteria andNomeNotIn(List<String> values) {
			addCriterion("nome not in", values, "nome");
			return (Criteria) this;
		}

		public Criteria andNomeBetween(String value1, String value2) {
			addCriterion("nome between", value1, value2, "nome");
			return (Criteria) this;
		}

		public Criteria andNomeNotBetween(String value1, String value2) {
			addCriterion("nome not between", value1, value2, "nome");
			return (Criteria) this;
		}

		public Criteria andDescrizioneIsNull() {
			addCriterion("descrizione is null");
			return (Criteria) this;
		}

		public Criteria andDescrizioneIsNotNull() {
			addCriterion("descrizione is not null");
			return (Criteria) this;
		}

		public Criteria andDescrizioneEqualTo(String value) {
			addCriterion("descrizione =", value, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneNotEqualTo(String value) {
			addCriterion("descrizione <>", value, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneGreaterThan(String value) {
			addCriterion("descrizione >", value, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneGreaterThanOrEqualTo(String value) {
			addCriterion("descrizione >=", value, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneLessThan(String value) {
			addCriterion("descrizione <", value, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneLessThanOrEqualTo(String value) {
			addCriterion("descrizione <=", value, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneLike(String value) {
			addCriterion("descrizione like", value, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneNotLike(String value) {
			addCriterion("descrizione not like", value, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneIn(List<String> values) {
			addCriterion("descrizione in", values, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneNotIn(List<String> values) {
			addCriterion("descrizione not in", values, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneBetween(String value1, String value2) {
			addCriterion("descrizione between", value1, value2, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDescrizioneNotBetween(String value1, String value2) {
			addCriterion("descrizione not between", value1, value2, "descrizione");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaIsNull() {
			addCriterion("data_inizio_validita is null");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaIsNotNull() {
			addCriterion("data_inizio_validita is not null");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaEqualTo(Date value) {
			addCriterion("data_inizio_validita =", value, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaNotEqualTo(Date value) {
			addCriterion("data_inizio_validita <>", value, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaGreaterThan(Date value) {
			addCriterion("data_inizio_validita >", value, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaGreaterThanOrEqualTo(Date value) {
			addCriterion("data_inizio_validita >=", value, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaLessThan(Date value) {
			addCriterion("data_inizio_validita <", value, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaLessThanOrEqualTo(Date value) {
			addCriterion("data_inizio_validita <=", value, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaIn(List<Date> values) {
			addCriterion("data_inizio_validita in", values, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaNotIn(List<Date> values) {
			addCriterion("data_inizio_validita not in", values, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaBetween(Date value1, Date value2) {
			addCriterion("data_inizio_validita between", value1, value2, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaNotBetween(Date value1, Date value2) {
			addCriterion("data_inizio_validita not between", value1, value2, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaIsNull() {
			addCriterion("data_fine_validita is null");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaIsNotNull() {
			addCriterion("data_fine_validita is not null");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaEqualTo(Date value) {
			addCriterion("data_fine_validita =", value, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaNotEqualTo(Date value) {
			addCriterion("data_fine_validita <>", value, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaGreaterThan(Date value) {
			addCriterion("data_fine_validita >", value, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaGreaterThanOrEqualTo(Date value) {
			addCriterion("data_fine_validita >=", value, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaLessThan(Date value) {
			addCriterion("data_fine_validita <", value, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaLessThanOrEqualTo(Date value) {
			addCriterion("data_fine_validita <=", value, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaIn(List<Date> values) {
			addCriterion("data_fine_validita in", values, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaNotIn(List<Date> values) {
			addCriterion("data_fine_validita not in", values, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaBetween(Date value1, Date value2) {
			addCriterion("data_fine_validita between", value1, value2, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaNotBetween(Date value1, Date value2) {
			addCriterion("data_fine_validita not between", value1, value2, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneIsNull() {
			addCriterion("data_creazione is null");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneIsNotNull() {
			addCriterion("data_creazione is not null");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneEqualTo(Date value) {
			addCriterion("data_creazione =", value, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneNotEqualTo(Date value) {
			addCriterion("data_creazione <>", value, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneGreaterThan(Date value) {
			addCriterion("data_creazione >", value, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneGreaterThanOrEqualTo(Date value) {
			addCriterion("data_creazione >=", value, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneLessThan(Date value) {
			addCriterion("data_creazione <", value, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneLessThanOrEqualTo(Date value) {
			addCriterion("data_creazione <=", value, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneIn(List<Date> values) {
			addCriterion("data_creazione in", values, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneNotIn(List<Date> values) {
			addCriterion("data_creazione not in", values, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneBetween(Date value1, Date value2) {
			addCriterion("data_creazione between", value1, value2, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneNotBetween(Date value1, Date value2) {
			addCriterion("data_creazione not between", value1, value2, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoIsNull() {
			addCriterion("data_aggiornamento is null");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoIsNotNull() {
			addCriterion("data_aggiornamento is not null");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoEqualTo(Date value) {
			addCriterion("data_aggiornamento =", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoNotEqualTo(Date value) {
			addCriterion("data_aggiornamento <>", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoGreaterThan(Date value) {
			addCriterion("data_aggiornamento >", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoGreaterThanOrEqualTo(Date value) {
			addCriterion("data_aggiornamento >=", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoLessThan(Date value) {
			addCriterion("data_aggiornamento <", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoLessThanOrEqualTo(Date value) {
			addCriterion("data_aggiornamento <=", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoIn(List<Date> values) {
			addCriterion("data_aggiornamento in", values, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoNotIn(List<Date> values) {
			addCriterion("data_aggiornamento not in", values, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoBetween(Date value1, Date value2) {
			addCriterion("data_aggiornamento between", value1, value2, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoNotBetween(Date value1, Date value2) {
			addCriterion("data_aggiornamento not between", value1, value2, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneIsNull() {
			addCriterion("data_cancellazione is null");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneIsNotNull() {
			addCriterion("data_cancellazione is not null");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneEqualTo(Date value) {
			addCriterion("data_cancellazione =", value, "dataCancellazione");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneNotEqualTo(Date value) {
			addCriterion("data_cancellazione <>", value, "dataCancellazione");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneGreaterThan(Date value) {
			addCriterion("data_cancellazione >", value, "dataCancellazione");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneGreaterThanOrEqualTo(Date value) {
			addCriterion("data_cancellazione >=", value, "dataCancellazione");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneLessThan(Date value) {
			addCriterion("data_cancellazione <", value, "dataCancellazione");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneLessThanOrEqualTo(Date value) {
			addCriterion("data_cancellazione <=", value, "dataCancellazione");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneIn(List<Date> values) {
			addCriterion("data_cancellazione in", values, "dataCancellazione");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneNotIn(List<Date> values) {
			addCriterion("data_cancellazione not in", values, "dataCancellazione");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneBetween(Date value1, Date value2) {
			addCriterion("data_cancellazione between", value1, value2, "dataCancellazione");
			return (Criteria) this;
		}

		public Criteria andDataCancellazioneNotBetween(Date value1, Date value2) {
			addCriterion("data_cancellazione not between", value1, value2, "dataCancellazione");
			return (Criteria) this;
		}

		public Criteria andSenderInstitutionIsNull() {
			addCriterion("sender_institution is null");
			return (Criteria) this;
		}

		public Criteria andSenderInstitutionIsNotNull() {
			addCriterion("sender_institution is not null");
			return (Criteria) this;
		}

		public Criteria andSenderInstitutionEqualTo(String value) {
			addCriterion("sender_institution =", value, "senderInstitution");
			return (Criteria) this;
		}

		public Criteria andSenderInstitutionNotEqualTo(String value) {
			addCriterion("sender_institution <>", value, "senderInstitution");
			return (Criteria) this;
		}

		public Criteria andSenderInstitutionGreaterThan(String value) {
			addCriterion("sender_institution >", value, "senderInstitution");
			return (Criteria) this;
		}

		public Criteria andSenderInstitutionGreaterThanOrEqualTo(String value) {
			addCriterion("sender_institution >=", value, "senderInstitution");
			return (Criteria) this;
		}

		public Criteria andSenderInstitutionLessThan(String value) {
			addCriterion("sender_institution <", value, "senderInstitution");
			return (Criteria) this;
		}

		public Criteria andSenderInstitutionLessThanOrEqualTo(String value) {
			addCriterion("sender_institution <=", value, "senderInstitution");
			return (Criteria) this;
		}

		public Criteria andSenderInstitutionLike(String value) {
			addCriterion("sender_institution like", value, "senderInstitution");
			return (Criteria) this;
		}

		public Criteria andSenderInstitutionNotLike(String value) {
			addCriterion("sender_institution not like", value, "senderInstitution");
			return (Criteria) this;
		}

		public Criteria andSenderInstitutionIn(List<String> values) {
			addCriterion("sender_institution in", values, "senderInstitution");
			return (Criteria) this;
		}

		public Criteria andSenderInstitutionNotIn(List<String> values) {
			addCriterion("sender_institution not in", values, "senderInstitution");
			return (Criteria) this;
		}

		public Criteria andSenderInstitutionBetween(String value1, String value2) {
			addCriterion("sender_institution between", value1, value2, "senderInstitution");
			return (Criteria) this;
		}

		public Criteria andSenderInstitutionNotBetween(String value1, String value2) {
			addCriterion("sender_institution not between", value1, value2, "senderInstitution");
			return (Criteria) this;
		}

		public Criteria andFolderIdentificationCodeIsNull() {
			addCriterion("folder_identification_code is null");
			return (Criteria) this;
		}

		public Criteria andFolderIdentificationCodeIsNotNull() {
			addCriterion("folder_identification_code is not null");
			return (Criteria) this;
		}

		public Criteria andFolderIdentificationCodeEqualTo(String value) {
			addCriterion("folder_identification_code =", value, "folderIdentificationCode");
			return (Criteria) this;
		}

		public Criteria andFolderIdentificationCodeNotEqualTo(String value) {
			addCriterion("folder_identification_code <>", value, "folderIdentificationCode");
			return (Criteria) this;
		}

		public Criteria andFolderIdentificationCodeGreaterThan(String value) {
			addCriterion("folder_identification_code >", value, "folderIdentificationCode");
			return (Criteria) this;
		}

		public Criteria andFolderIdentificationCodeGreaterThanOrEqualTo(String value) {
			addCriterion("folder_identification_code >=", value, "folderIdentificationCode");
			return (Criteria) this;
		}

		public Criteria andFolderIdentificationCodeLessThan(String value) {
			addCriterion("folder_identification_code <", value, "folderIdentificationCode");
			return (Criteria) this;
		}

		public Criteria andFolderIdentificationCodeLessThanOrEqualTo(String value) {
			addCriterion("folder_identification_code <=", value, "folderIdentificationCode");
			return (Criteria) this;
		}

		public Criteria andFolderIdentificationCodeLike(String value) {
			addCriterion("folder_identification_code like", value, "folderIdentificationCode");
			return (Criteria) this;
		}

		public Criteria andFolderIdentificationCodeNotLike(String value) {
			addCriterion("folder_identification_code not like", value, "folderIdentificationCode");
			return (Criteria) this;
		}

		public Criteria andFolderIdentificationCodeIn(List<String> values) {
			addCriterion("folder_identification_code in", values, "folderIdentificationCode");
			return (Criteria) this;
		}

		public Criteria andFolderIdentificationCodeNotIn(List<String> values) {
			addCriterion("folder_identification_code not in", values, "folderIdentificationCode");
			return (Criteria) this;
		}

		public Criteria andFolderIdentificationCodeBetween(String value1, String value2) {
			addCriterion("folder_identification_code between", value1, value2, "folderIdentificationCode");
			return (Criteria) this;
		}

		public Criteria andFolderIdentificationCodeNotBetween(String value1, String value2) {
			addCriterion("folder_identification_code not between", value1, value2, "folderIdentificationCode");
			return (Criteria) this;
		}

		public Criteria andIdSistemaRegionaleIsNull() {
			addCriterion("id_sistema_regionale is null");
			return (Criteria) this;
		}

		public Criteria andIdSistemaRegionaleIsNotNull() {
			addCriterion("id_sistema_regionale is not null");
			return (Criteria) this;
		}

		public Criteria andIdSistemaRegionaleEqualTo(String value) {
			addCriterion("id_sistema_regionale =", value, "idSistemaRegionale");
			return (Criteria) this;
		}

		public Criteria andIdSistemaRegionaleNotEqualTo(String value) {
			addCriterion("id_sistema_regionale <>", value, "idSistemaRegionale");
			return (Criteria) this;
		}

		public Criteria andIdSistemaRegionaleGreaterThan(String value) {
			addCriterion("id_sistema_regionale >", value, "idSistemaRegionale");
			return (Criteria) this;
		}

		public Criteria andIdSistemaRegionaleGreaterThanOrEqualTo(String value) {
			addCriterion("id_sistema_regionale >=", value, "idSistemaRegionale");
			return (Criteria) this;
		}

		public Criteria andIdSistemaRegionaleLessThan(String value) {
			addCriterion("id_sistema_regionale <", value, "idSistemaRegionale");
			return (Criteria) this;
		}

		public Criteria andIdSistemaRegionaleLessThanOrEqualTo(String value) {
			addCriterion("id_sistema_regionale <=", value, "idSistemaRegionale");
			return (Criteria) this;
		}

		public Criteria andIdSistemaRegionaleLike(String value) {
			addCriterion("id_sistema_regionale like", value, "idSistemaRegionale");
			return (Criteria) this;
		}

		public Criteria andIdSistemaRegionaleNotLike(String value) {
			addCriterion("id_sistema_regionale not like", value, "idSistemaRegionale");
			return (Criteria) this;
		}

		public Criteria andIdSistemaRegionaleIn(List<String> values) {
			addCriterion("id_sistema_regionale in", values, "idSistemaRegionale");
			return (Criteria) this;
		}

		public Criteria andIdSistemaRegionaleNotIn(List<String> values) {
			addCriterion("id_sistema_regionale not in", values, "idSistemaRegionale");
			return (Criteria) this;
		}

		public Criteria andIdSistemaRegionaleBetween(String value1, String value2) {
			addCriterion("id_sistema_regionale between", value1, value2, "idSistemaRegionale");
			return (Criteria) this;
		}

		public Criteria andIdSistemaRegionaleNotBetween(String value1, String value2) {
			addCriterion("id_sistema_regionale not between", value1, value2, "idSistemaRegionale");
			return (Criteria) this;
		}

		public Criteria andCodiceLikeInsensitive(String value) {
			addCriterion("upper(codice) like", value.toUpperCase(), "codice");
			return (Criteria) this;
		}

		public Criteria andNomeLikeInsensitive(String value) {
			addCriterion("upper(nome) like", value.toUpperCase(), "nome");
			return (Criteria) this;
		}

		public Criteria andDescrizioneLikeInsensitive(String value) {
			addCriterion("upper(descrizione) like", value.toUpperCase(), "descrizione");
			return (Criteria) this;
		}

		public Criteria andSenderInstitutionLikeInsensitive(String value) {
			addCriterion("upper(sender_institution) like", value.toUpperCase(), "senderInstitution");
			return (Criteria) this;
		}

		public Criteria andFolderIdentificationCodeLikeInsensitive(String value) {
			addCriterion("upper(folder_identification_code) like", value.toUpperCase(), "folderIdentificationCode");
			return (Criteria) this;
		}

		public Criteria andIdSistemaRegionaleLikeInsensitive(String value) {
			addCriterion("upper(id_sistema_regionale) like", value.toUpperCase(), "idSistemaRegionale");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table gatefire.gatefire_d_applicazione
	 * @mbg.generated  Wed May 18 11:29:35 CEST 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gatefire.gatefire_d_applicazione
     *
     * @mbg.generated do_not_delete_during_merge Wed Nov 25 11:01:29 CET 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}