/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gatefire.dbhelper.model;

import java.util.Date;

public class GatefireTAmministratore {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_t_amministratore.id
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_t_amministratore.cognome
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	private String cognome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_t_amministratore.nome
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	private String nome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_t_amministratore.email
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_t_amministratore.password
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_t_amministratore.note
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_t_amministratore.data_fine_validita
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	private Date dataFineValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_t_amministratore.data_creazione
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_t_amministratore.data_aggiornamento
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	private Date dataAggiornamento;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_t_amministratore.id
	 * @return  the value of gatefire.gatefire_t_amministratore.id
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_t_amministratore.id
	 * @param id  the value for gatefire.gatefire_t_amministratore.id
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_t_amministratore.cognome
	 * @return  the value of gatefire.gatefire_t_amministratore.cognome
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public String getCognome() {
		return cognome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_t_amministratore.cognome
	 * @param cognome  the value for gatefire.gatefire_t_amministratore.cognome
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_t_amministratore.nome
	 * @return  the value of gatefire.gatefire_t_amministratore.nome
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public String getNome() {
		return nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_t_amministratore.nome
	 * @param nome  the value for gatefire.gatefire_t_amministratore.nome
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_t_amministratore.email
	 * @return  the value of gatefire.gatefire_t_amministratore.email
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_t_amministratore.email
	 * @param email  the value for gatefire.gatefire_t_amministratore.email
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_t_amministratore.password
	 * @return  the value of gatefire.gatefire_t_amministratore.password
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_t_amministratore.password
	 * @param password  the value for gatefire.gatefire_t_amministratore.password
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_t_amministratore.note
	 * @return  the value of gatefire.gatefire_t_amministratore.note
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_t_amministratore.note
	 * @param note  the value for gatefire.gatefire_t_amministratore.note
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_t_amministratore.data_fine_validita
	 * @return  the value of gatefire.gatefire_t_amministratore.data_fine_validita
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public Date getDataFineValidita() {
		return dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_t_amministratore.data_fine_validita
	 * @param dataFineValidita  the value for gatefire.gatefire_t_amministratore.data_fine_validita
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public void setDataFineValidita(Date dataFineValidita) {
		this.dataFineValidita = dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_t_amministratore.data_creazione
	 * @return  the value of gatefire.gatefire_t_amministratore.data_creazione
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_t_amministratore.data_creazione
	 * @param dataCreazione  the value for gatefire.gatefire_t_amministratore.data_creazione
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_t_amministratore.data_aggiornamento
	 * @return  the value of gatefire.gatefire_t_amministratore.data_aggiornamento
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_t_amministratore.data_aggiornamento
	 * @param dataAggiornamento  the value for gatefire.gatefire_t_amministratore.data_aggiornamento
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}
}