/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gatefire.dbhelper.model;

import java.util.Date;
import java.util.List;

public class GatefireDRepository {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_repository.codice
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	private String codice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_repository.nome
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	private String nome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_repository.descrizione
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	private String descrizione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_repository.data_inizio_validita
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	private Date dataInizioValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_repository.data_fine_validita
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	private Date dataFineValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_repository.data_creazione
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_repository.data_aggiornamento
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	private Date dataAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_repository.data_cancellazione
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_repository.collocazione
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	private String collocazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_repository.authentication_required
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	private Boolean authenticationRequired;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_repository.gestione_consensi
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	private String gestioneConsensi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_repository.gestione_id_episodio
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	private Boolean gestioneIdEpisodio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_repository.tipo_repository
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	private String tipoRepository;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_repository.codice
	 * @return  the value of gatefire.gatefire_d_repository.codice
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public String getCodice() {
		return codice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_repository.codice
	 * @param codice  the value for gatefire.gatefire_d_repository.codice
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public void setCodice(String codice) {
		this.codice = codice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_repository.nome
	 * @return  the value of gatefire.gatefire_d_repository.nome
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public String getNome() {
		return nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_repository.nome
	 * @param nome  the value for gatefire.gatefire_d_repository.nome
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_repository.descrizione
	 * @return  the value of gatefire.gatefire_d_repository.descrizione
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public String getDescrizione() {
		return descrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_repository.descrizione
	 * @param descrizione  the value for gatefire.gatefire_d_repository.descrizione
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_repository.data_inizio_validita
	 * @return  the value of gatefire.gatefire_d_repository.data_inizio_validita
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public Date getDataInizioValidita() {
		return dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_repository.data_inizio_validita
	 * @param dataInizioValidita  the value for gatefire.gatefire_d_repository.data_inizio_validita
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public void setDataInizioValidita(Date dataInizioValidita) {
		this.dataInizioValidita = dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_repository.data_fine_validita
	 * @return  the value of gatefire.gatefire_d_repository.data_fine_validita
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public Date getDataFineValidita() {
		return dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_repository.data_fine_validita
	 * @param dataFineValidita  the value for gatefire.gatefire_d_repository.data_fine_validita
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public void setDataFineValidita(Date dataFineValidita) {
		this.dataFineValidita = dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_repository.data_creazione
	 * @return  the value of gatefire.gatefire_d_repository.data_creazione
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_repository.data_creazione
	 * @param dataCreazione  the value for gatefire.gatefire_d_repository.data_creazione
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_repository.data_aggiornamento
	 * @return  the value of gatefire.gatefire_d_repository.data_aggiornamento
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_repository.data_aggiornamento
	 * @param dataAggiornamento  the value for gatefire.gatefire_d_repository.data_aggiornamento
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_repository.data_cancellazione
	 * @return  the value of gatefire.gatefire_d_repository.data_cancellazione
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_repository.data_cancellazione
	 * @param dataCancellazione  the value for gatefire.gatefire_d_repository.data_cancellazione
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_repository.collocazione
	 * @return  the value of gatefire.gatefire_d_repository.collocazione
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public String getCollocazione() {
		return collocazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_repository.collocazione
	 * @param collocazione  the value for gatefire.gatefire_d_repository.collocazione
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public void setCollocazione(String collocazione) {
		this.collocazione = collocazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_repository.authentication_required
	 * @return  the value of gatefire.gatefire_d_repository.authentication_required
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public Boolean getAuthenticationRequired() {
		return authenticationRequired;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_repository.authentication_required
	 * @param authenticationRequired  the value for gatefire.gatefire_d_repository.authentication_required
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public void setAuthenticationRequired(Boolean authenticationRequired) {
		this.authenticationRequired = authenticationRequired;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_repository.gestione_consensi
	 * @return  the value of gatefire.gatefire_d_repository.gestione_consensi
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public String getGestioneConsensi() {
		return gestioneConsensi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_repository.gestione_consensi
	 * @param gestioneConsensi  the value for gatefire.gatefire_d_repository.gestione_consensi
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public void setGestioneConsensi(String gestioneConsensi) {
		this.gestioneConsensi = gestioneConsensi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_repository.gestione_id_episodio
	 * @return  the value of gatefire.gatefire_d_repository.gestione_id_episodio
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public Boolean getGestioneIdEpisodio() {
		return gestioneIdEpisodio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_repository.gestione_id_episodio
	 * @param gestioneIdEpisodio  the value for gatefire.gatefire_d_repository.gestione_id_episodio
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public void setGestioneIdEpisodio(Boolean gestioneIdEpisodio) {
		this.gestioneIdEpisodio = gestioneIdEpisodio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_repository.tipo_repository
	 * @return  the value of gatefire.gatefire_d_repository.tipo_repository
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public String getTipoRepository() {
		return tipoRepository;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_repository.tipo_repository
	 * @param tipoRepository  the value for gatefire.gatefire_d_repository.tipo_repository
	 * @mbg.generated  Mon May 30 12:48:36 CEST 2022
	 */
	public void setTipoRepository(String tipoRepository) {
		this.tipoRepository = tipoRepository;
	}

	private List<GatefireRRepositoryUri> repositoryUriList;

	public List<GatefireRRepositoryUri> getRepositoryUriList() {
		return repositoryUriList;
	}

	public void setRepositoryUriList(List<GatefireRRepositoryUri> repositoryUriList) {
		this.repositoryUriList = repositoryUriList;
	}

}