/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gatefire.dbhelper.model;

import java.util.Date;

public class GatefireTRuolo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_t_ruolo.codice
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	private String codice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_t_ruolo.descrizione
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	private String descrizione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_t_ruolo.data_creazione
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_t_ruolo.data_aggiornamento
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	private Date dataAggiornamento;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_t_ruolo.codice
	 * @return  the value of gatefire.gatefire_t_ruolo.codice
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public String getCodice() {
		return codice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_t_ruolo.codice
	 * @param codice  the value for gatefire.gatefire_t_ruolo.codice
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public void setCodice(String codice) {
		this.codice = codice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_t_ruolo.descrizione
	 * @return  the value of gatefire.gatefire_t_ruolo.descrizione
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public String getDescrizione() {
		return descrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_t_ruolo.descrizione
	 * @param descrizione  the value for gatefire.gatefire_t_ruolo.descrizione
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_t_ruolo.data_creazione
	 * @return  the value of gatefire.gatefire_t_ruolo.data_creazione
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_t_ruolo.data_creazione
	 * @param dataCreazione  the value for gatefire.gatefire_t_ruolo.data_creazione
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_t_ruolo.data_aggiornamento
	 * @return  the value of gatefire.gatefire_t_ruolo.data_aggiornamento
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_t_ruolo.data_aggiornamento
	 * @param dataAggiornamento  the value for gatefire.gatefire_t_ruolo.data_aggiornamento
	 * @mbg.generated  Fri Jan 29 11:46:20 CET 2021
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}
}