/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gatefire.dbhelper.model;

import java.util.Date;

public class GatefireLEventoStep extends GatefireLEventoStepKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento_step.data_creazione
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento_step.descrizione
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	private String descrizione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento_step.return_code
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	private String returnCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento_step.return_code_descrizione
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	private String returnCodeDescrizione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento_step.codice_stato_evento_log
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	private String codiceStatoEventoLog;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento_step.codice_tipo_passo_evento_log
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	private String codiceTipoPassoEventoLog;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento_step.data_cancellazione
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento_step.data_creazione
	 * @return  the value of gatefire.gatefire_l_evento_step.data_creazione
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento_step.data_creazione
	 * @param dataCreazione  the value for gatefire.gatefire_l_evento_step.data_creazione
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento_step.descrizione
	 * @return  the value of gatefire.gatefire_l_evento_step.descrizione
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	public String getDescrizione() {
		return descrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento_step.descrizione
	 * @param descrizione  the value for gatefire.gatefire_l_evento_step.descrizione
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento_step.return_code
	 * @return  the value of gatefire.gatefire_l_evento_step.return_code
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	public String getReturnCode() {
		return returnCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento_step.return_code
	 * @param returnCode  the value for gatefire.gatefire_l_evento_step.return_code
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	public void setReturnCode(String returnCode) {
		this.returnCode = returnCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento_step.return_code_descrizione
	 * @return  the value of gatefire.gatefire_l_evento_step.return_code_descrizione
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	public String getReturnCodeDescrizione() {
		return returnCodeDescrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento_step.return_code_descrizione
	 * @param returnCodeDescrizione  the value for gatefire.gatefire_l_evento_step.return_code_descrizione
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	public void setReturnCodeDescrizione(String returnCodeDescrizione) {
		this.returnCodeDescrizione = returnCodeDescrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento_step.codice_stato_evento_log
	 * @return  the value of gatefire.gatefire_l_evento_step.codice_stato_evento_log
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	public String getCodiceStatoEventoLog() {
		return codiceStatoEventoLog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento_step.codice_stato_evento_log
	 * @param codiceStatoEventoLog  the value for gatefire.gatefire_l_evento_step.codice_stato_evento_log
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	public void setCodiceStatoEventoLog(String codiceStatoEventoLog) {
		this.codiceStatoEventoLog = codiceStatoEventoLog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento_step.codice_tipo_passo_evento_log
	 * @return  the value of gatefire.gatefire_l_evento_step.codice_tipo_passo_evento_log
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	public String getCodiceTipoPassoEventoLog() {
		return codiceTipoPassoEventoLog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento_step.codice_tipo_passo_evento_log
	 * @param codiceTipoPassoEventoLog  the value for gatefire.gatefire_l_evento_step.codice_tipo_passo_evento_log
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	public void setCodiceTipoPassoEventoLog(String codiceTipoPassoEventoLog) {
		this.codiceTipoPassoEventoLog = codiceTipoPassoEventoLog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento_step.data_cancellazione
	 * @return  the value of gatefire.gatefire_l_evento_step.data_cancellazione
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento_step.data_cancellazione
	 * @param dataCancellazione  the value for gatefire.gatefire_l_evento_step.data_cancellazione
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}