/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gatefire.dbhelper.model;

import java.util.Date;

public class GatefireRRepositoryUri {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gatefire.gatefire_r_repository_uri.id
	 * 
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gatefire.gatefire_r_repository_uri.codice_repository
	 * 
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	private String codiceRepository;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gatefire.gatefire_r_repository_uri.transazione
	 * 
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	private String transazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gatefire.gatefire_r_repository_uri.uri
	 * 
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	private String uri;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gatefire.gatefire_r_repository_uri.data_inizio_validita
	 * 
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	private Date dataInizioValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gatefire.gatefire_r_repository_uri.data_fine_validita
	 * 
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	private Date dataFineValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gatefire.gatefire_r_repository_uri.data_creazione
	 * 
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gatefire.gatefire_r_repository_uri.data_aggiornamento
	 * 
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	private Date dataAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gatefire.gatefire_r_repository_uri.data_cancellazione
	 * 
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gatefire.gatefire_r_repository_uri.id
	 * 
	 * @return the value of gatefire.gatefire_r_repository_uri.id
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gatefire.gatefire_r_repository_uri.id
	 * 
	 * @param id the value for gatefire.gatefire_r_repository_uri.id
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gatefire.gatefire_r_repository_uri.codice_repository
	 * 
	 * @return the value of gatefire.gatefire_r_repository_uri.codice_repository
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	public String getCodiceRepository() {
		return codiceRepository;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gatefire.gatefire_r_repository_uri.codice_repository
	 * 
	 * @param codiceRepository the value for
	 *                         gatefire.gatefire_r_repository_uri.codice_repository
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	public void setCodiceRepository(String codiceRepository) {
		this.codiceRepository = codiceRepository;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gatefire.gatefire_r_repository_uri.transazione
	 * 
	 * @return the value of gatefire.gatefire_r_repository_uri.transazione
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	public String getTransazione() {
		return transazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gatefire.gatefire_r_repository_uri.transazione
	 * 
	 * @param transazione the value for
	 *                    gatefire.gatefire_r_repository_uri.transazione
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	public void setTransazione(String transazione) {
		this.transazione = transazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gatefire.gatefire_r_repository_uri.uri
	 * 
	 * @return the value of gatefire.gatefire_r_repository_uri.uri
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	public String getUri() {
		return uri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gatefire.gatefire_r_repository_uri.uri
	 * 
	 * @param uri the value for gatefire.gatefire_r_repository_uri.uri
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	public void setUri(String uri) {
		this.uri = uri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * gatefire.gatefire_r_repository_uri.data_inizio_validita
	 * 
	 * @return the value of gatefire.gatefire_r_repository_uri.data_inizio_validita
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	public Date getDataInizioValidita() {
		return dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gatefire.gatefire_r_repository_uri.data_inizio_validita
	 * 
	 * @param dataInizioValidita the value for
	 *                           gatefire.gatefire_r_repository_uri.data_inizio_validita
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	public void setDataInizioValidita(Date dataInizioValidita) {
		this.dataInizioValidita = dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gatefire.gatefire_r_repository_uri.data_fine_validita
	 * 
	 * @return the value of gatefire.gatefire_r_repository_uri.data_fine_validita
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	public Date getDataFineValidita() {
		return dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gatefire.gatefire_r_repository_uri.data_fine_validita
	 * 
	 * @param dataFineValidita the value for
	 *                         gatefire.gatefire_r_repository_uri.data_fine_validita
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	public void setDataFineValidita(Date dataFineValidita) {
		this.dataFineValidita = dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gatefire.gatefire_r_repository_uri.data_creazione
	 * 
	 * @return the value of gatefire.gatefire_r_repository_uri.data_creazione
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gatefire.gatefire_r_repository_uri.data_creazione
	 * 
	 * @param dataCreazione the value for
	 *                      gatefire.gatefire_r_repository_uri.data_creazione
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gatefire.gatefire_r_repository_uri.data_aggiornamento
	 * 
	 * @return the value of gatefire.gatefire_r_repository_uri.data_aggiornamento
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gatefire.gatefire_r_repository_uri.data_aggiornamento
	 * 
	 * @param dataAggiornamento the value for
	 *                          gatefire.gatefire_r_repository_uri.data_aggiornamento
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gatefire.gatefire_r_repository_uri.data_cancellazione
	 * 
	 * @return the value of gatefire.gatefire_r_repository_uri.data_cancellazione
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gatefire.gatefire_r_repository_uri.data_cancellazione
	 * 
	 * @param dataCancellazione the value for
	 *                          gatefire.gatefire_r_repository_uri.data_cancellazione
	 * @mbg.generated Wed Apr 13 14:49:35 CEST 2022
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	@Override
	public String toString() {
		return "GatefireRRepositoryUri [id=" + id + ", codiceRepository=" + codiceRepository + ", transazione="
				+ transazione + ", uri=" + uri + ", dataInizioValidita=" + dataInizioValidita + ", dataFineValidita="
				+ dataFineValidita + ", dataCreazione=" + dataCreazione + ", dataAggiornamento=" + dataAggiornamento
				+ ", dataCancellazione=" + dataCancellazione + "]";
	}

}