/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gatefire.dbhelper.model;

public class GatefireDCaCollocazioneDominioKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_ca_collocazione_dominio.codice_ca
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	private String codiceCa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_ca_collocazione_dominio.tipo_funzione
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	private String tipoFunzione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_ca_collocazione_dominio.collocazione
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	private String collocazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_d_ca_collocazione_dominio.dominio
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	private String dominio;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_ca_collocazione_dominio.codice_ca
	 * @return  the value of gatefire.gatefire_d_ca_collocazione_dominio.codice_ca
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	public String getCodiceCa() {
		return codiceCa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_ca_collocazione_dominio.codice_ca
	 * @param codiceCa  the value for gatefire.gatefire_d_ca_collocazione_dominio.codice_ca
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	public void setCodiceCa(String codiceCa) {
		this.codiceCa = codiceCa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_ca_collocazione_dominio.tipo_funzione
	 * @return  the value of gatefire.gatefire_d_ca_collocazione_dominio.tipo_funzione
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	public String getTipoFunzione() {
		return tipoFunzione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_ca_collocazione_dominio.tipo_funzione
	 * @param tipoFunzione  the value for gatefire.gatefire_d_ca_collocazione_dominio.tipo_funzione
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	public void setTipoFunzione(String tipoFunzione) {
		this.tipoFunzione = tipoFunzione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_ca_collocazione_dominio.collocazione
	 * @return  the value of gatefire.gatefire_d_ca_collocazione_dominio.collocazione
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	public String getCollocazione() {
		return collocazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_ca_collocazione_dominio.collocazione
	 * @param collocazione  the value for gatefire.gatefire_d_ca_collocazione_dominio.collocazione
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	public void setCollocazione(String collocazione) {
		this.collocazione = collocazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_d_ca_collocazione_dominio.dominio
	 * @return  the value of gatefire.gatefire_d_ca_collocazione_dominio.dominio
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	public String getDominio() {
		return dominio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_d_ca_collocazione_dominio.dominio
	 * @param dominio  the value for gatefire.gatefire_d_ca_collocazione_dominio.dominio
	 * @mbg.generated  Thu Apr 01 10:52:48 CEST 2021
	 */
	public void setDominio(String dominio) {
		this.dominio = dominio;
	}
}