/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gatefire.dbhelper.model;

public class GatefireLEventoStepKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento_step.id
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gatefire.gatefire_l_evento_step.id_evento
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	private Long idEvento;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento_step.id
	 * @return  the value of gatefire.gatefire_l_evento_step.id
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento_step.id
	 * @param id  the value for gatefire.gatefire_l_evento_step.id
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gatefire.gatefire_l_evento_step.id_evento
	 * @return  the value of gatefire.gatefire_l_evento_step.id_evento
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	public Long getIdEvento() {
		return idEvento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gatefire.gatefire_l_evento_step.id_evento
	 * @param idEvento  the value for gatefire.gatefire_l_evento_step.id_evento
	 * @mbg.generated  Wed Nov 25 10:50:37 CET 2020
	 */
	public void setIdEvento(Long idEvento) {
		this.idEvento = idEvento;
	}
}