package it.csi.gatefire.repository.assertion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2021-03-29T15:46:33.456+02:00
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://ws.apache.org/axis2", name = "wso2carbon-stsPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Wso2CarbonStsPortType {

    @WebMethod(operationName = "CancelToken", action = "http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Cancel")
    @Action(input = "http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Cancel", output = "urn:CancelTokenResponse")
    @WebResult(name = "RequestSecurityTokenResponse", targetNamespace = "http://schemas.xmlsoap.org/ws/2005/02/trust", partName = "parameters")
    public RequestSecurityTokenResponseType cancelToken(

        @WebParam(partName = "parameters", name = "RequestSecurityToken", targetNamespace = "http://schemas.xmlsoap.org/ws/2005/02/trust")
        RequestSecurityTokenType parameters
    );

    @WebMethod(operationName = "ValidateToken", action = "http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Validate")
    @Action(input = "http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Validate", output = "urn:ValidateTokenResponse")
    @WebResult(name = "RequestSecurityTokenResponse", targetNamespace = "http://schemas.xmlsoap.org/ws/2005/02/trust", partName = "parameters")
    public RequestSecurityTokenResponseType validateToken(

        @WebParam(partName = "parameters", name = "RequestSecurityToken", targetNamespace = "http://schemas.xmlsoap.org/ws/2005/02/trust")
        RequestSecurityTokenType parameters
    );

    @WebMethod(operationName = "RenewToken", action = "http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Renew")
    @Action(input = "http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Renew", output = "urn:RenewTokenResponse")
    @WebResult(name = "RequestSecurityTokenResponse", targetNamespace = "http://schemas.xmlsoap.org/ws/2005/02/trust", partName = "parameters")
    public RequestSecurityTokenResponseType renewToken(

        @WebParam(partName = "parameters", name = "RequestSecurityToken", targetNamespace = "http://schemas.xmlsoap.org/ws/2005/02/trust")
        RequestSecurityTokenType parameters
    );

    @WebMethod(operationName = "IssueToken", action = "http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Issue")
    @Action(input = "http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Issue", output = "urn:IssueTokenResponse")
    @WebResult(name = "RequestSecurityTokenResponse", targetNamespace = "http://schemas.xmlsoap.org/ws/2005/02/trust", partName = "parameters")
    public RequestSecurityTokenResponseType issueToken(

        @WebParam(partName = "parameters", name = "RequestSecurityToken", targetNamespace = "http://schemas.xmlsoap.org/ws/2005/02/trust")
        RequestSecurityTokenType parameters
    );
}
